// 游戏开发与游戏设计名言集（三语版）
// 每条包含：zh（中文）、en（英文原文）、ja（日文）

export interface Quote {
	zh: string;
	en: string;
	ja: string;
	author: string;
	source?: string;
}

export const quotes: Quote[] = [
	{
		zh: "游戏设计就是创造有趣决策的艺术。",
		en: "Game design is the art of creating interesting decisions.",
		ja: "ゲームデザインとは、興味深い決断を生み出す技術である。",
		author: "席德·梅尔（Sid Meier）",
		source: "《文明》之父",
	},
	{
		zh: "游戏就是一系列有趣的选择。",
		en: "A game is a series of interesting choices.",
		ja: "ゲームとは、興味深い選択の連続である。",
		author: "席德·梅尔（Sid Meier）",
		source: "《文明》",
	},
	{
		zh: "应该让玩家觉得自己聪明，而不是让设计师显得聪明。",
		en: "The player should feel smart, not the designer.",
		ja: "プレイヤーが賢くなったと感じるべきで、デザイナーが賢く見えるべきではない。",
		author: "乔纳森·布洛（Jonathan Blow）",
		source: "《见证者》《时空幻境》",
	},
	{
		zh: "游戏不需要\u201C好玩\u201D才算好，它只需要让人沉浸其中。",
		en: "Games don't need to be fun to be good. They just need to be engaging.",
		ja: "ゲームは「楽しい」だけが全てではない。没入感があれば良いゲームと言える。",
		author: "拉夫·科斯特（Raph Koster）",
		source: "《游戏设计的乐趣理论》",
	},
	{
		zh: "乐趣不过是学习的另一种说法。",
		en: "Fun is just another word for learning.",
		ja: "楽しさとは、学習の別名に過ぎない。",
		author: "拉夫·科斯特（Raph Koster）",
		source: "《游戏设计的乐趣理论》",
	},
	{
		zh: "最好的游戏是那些无需言语就能讲述故事的作品。",
		en: "The best games are those that tell stories without words.",
		ja: "最高のゲームとは、言葉を使わずに物語を語るものである。",
		author: "陈星汉（Jenova Chen）",
		source: "《风之旅人》《光·遇》",
	},
	{
		zh: "约束激发创造力。限制是发明之母。",
		en: "Constraints breed creativity. Restrictions are the mother of invention.",
		ja: "制約が創造性を生む。制限は発明の母である。",
		author: "马库斯·佩尔松（Notch）",
		source: "《我的世界》",
	},
	{
		zh: "迭代是游戏开发中最重要的事：做出来，测试，修改，重复。",
		en: "Iteration is the most important thing in game development: make it, test it, change it, repeat.",
		ja: "ゲーム開発で最も重要なのは反復である。作って、テストして、修正して、繰り返す。",
		author: "汤米·雷芬斯（Tommy Refenes）",
		source: "《超级肉肉哥》",
	},
	{
		zh: "跳票的游戏最终会变好，但糟糕的游戏永远糟糕。",
		en: "A delayed game is eventually good, but a rushed game is forever bad.",
		ja: "遅れたゲームはいつか良くなるが、急いで出したゲームは永遠に悪いままだ。",
		author: "宫本茂（Shigeru Miyamoto）",
		source: "任天堂",
	},
	{
		zh: "游戏的本质是玩家必须克服的一套规则。",
		en: "A game is a set of rules that the player must overcome.",
		ja: "ゲームとは、プレイヤーが克服すべきルールの集合である。",
		author: "杰西·谢尔（Jesse Schell）",
		source: "《游戏设计艺术》",
	},
	{
		zh: "好的游戏设计是让玩家做出的每个选择都有意义、有后果。",
		en: "Good game design means making every player choice meaningful and consequential.",
		ja: "良いゲームデザインとは、プレイヤーの選択一つ一つに意味と結果があることだ。",
		author: "沃伦·斯佩克特（Warren Spector）",
		source: "《杀出重围》",
	},
	{
		zh: "你的头一万个游戏是最难的，之后就会容易一些。",
		en: "Your first ten thousand games are the hardest, then it gets a bit easier.",
		ja: "最初の一万本のゲームが一番難しい。その後は少し楽になる。",
		author: "改编自 井山裕太",
		source: "围棋 / 游戏设计通用",
	},
	{
		zh: "关卡设计是在玩家不知不觉中引导他们的艺术。",
		en: "Level design is the art of guiding the player without them knowing it.",
		ja: "レベルデザインとは、プレイヤーに気付かれずに導く技術である。",
		author: "佚名关卡设计师",
		source: "关卡设计箴言",
	},
	{
		zh: "尽早原型化，频繁原型化。一个糟糕的原型和好的原型一样能告诉你很多。",
		en: "Prototype early, prototype often. A bad prototype tells you as much as a good one.",
		ja: "早くプロトタイプを作れ、頻繁に作れ。悪いプロトタイプも良いものと同じくらい多くのことを教えてくれる。",
		author: "布伦达·罗梅罗（Brenda Romero）",
		source: "游戏设计师 / 教授",
	},
	{
		zh: "游戏设计师的工作是创造能产生有趣涌现行为的系统。",
		en: "The game designer's job is to create systems that produce interesting emergent behavior.",
		ja: "ゲームデザイナーの仕事は、面白い創発行動を生み出すシステムを作ることである。",
		author: "威尔·莱特（Will Wright）",
		source: "《模拟城市》《模拟人生》",
	},
	{
		zh: "完美不是无可增添，而是无可删减。",
		en: "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.",
		ja: "完璧とは、何も加えるものがない状態ではなく、何も取り除くものがない状態のことである。",
		author: "安托万·德·圣-埃克苏佩里",
		source: "游戏设计通用原则",
	},
	{
		zh: "游戏开发是 90% 的调试加上 10% 的假装自己知道在做什么。",
		en: "Game development is 90% debugging and 10% pretending you know what you're doing.",
		ja: "ゲーム開発は90%のデバッグと、10%の「自分が何をしているか分かっているふり」で成り立っている。",
		author: "匿名",
		source: "游戏开发者社区",
	},
	{
		zh: "预测未来的最好方式就是亲手实现它。",
		en: "The best way to predict the future is to create it.",
		ja: "未来を予測する最良の方法は、自らそれを創り出すことだ。",
		author: "改编自 艾伦·凯（Alan Kay）",
		source: "游戏开发实践",
	},
	{
		zh: "不要为自己设计。为那些从未玩过你游戏的人设计。",
		en: "Don't design for yourself. Design for someone who has never played your game.",
		ja: "自分のためではなく、あなたのゲームを一度も遊んだことのない人のためにデザインしろ。",
		author: "埃德蒙·麦克米伦（Edmund McMillen）",
		source: "《以撒的结合》",
	},
	{
		zh: "优雅的游戏里，每个系统都在支撑其他所有系统。",
		en: "In an elegant game, every system supports every other system.",
		ja: "洗練されたゲームでは、すべてのシステムが互いを支え合っている。",
		author: "泰南·西尔维斯特（Tynan Sylvester）",
		source: "《环世界》/《游戏设计实战》",
	},
	{
		zh: "叙事设计不是写一个故事，而是设计让故事得以涌现的条件。",
		en: "Narrative design is not about writing a story, but about designing the conditions for stories to emerge.",
		ja: "ナラティブデザインとは、物語を書くことではなく、物語が生まれるための条件を設計することである。",
		author: "皮特罗·波尔西内利（Pietro Polsinelli）",
		source: "《叙事设计漫谈》",
	},
	{
		zh: "游戏设计师工具箱里最强大的工具，是用别人的眼睛来看你的游戏。",
		en: "The most powerful tool in a game designer's toolbox is seeing your game through someone else's eyes.",
		ja: "ゲームデザイナーの道具箱で最も強力な道具は、他人の目を通して自分のゲームを見ることだ。",
		author: "杰西·谢尔（Jesse Schell）",
		source: "《游戏设计艺术》",
	},
	{
		zh: "好的关卡设计不用教程来教。环境本身会告诉玩家该做什么。",
		en: "Good level design doesn't need tutorials. The environment itself tells the player what to do.",
		ja: "良いレベルデザインにチュートリアルは不要だ。環境そのものがプレイヤーに何をすべきかを教えてくれる。",
		author: "佚名",
		source: "关卡设计通用",
	},
	{
		zh: "简洁是游戏机制的终极优雅。一个按钮如果按对了地方，就足够了。",
		en: "Simplicity is the ultimate elegance of game mechanics. One button, placed in the right spot, is enough.",
		ja: "シンプルさはゲームメカニクスの究極の洗練である。正しい場所に置かれた一つのボタンで十分だ。",
		author: "扎克·盖奇（Zach Gage）",
		source: "《SpellTower》《Typeshift》",
	},
	{
		zh: "世界观设计不是创造一张地图，而是为可信的因果逻辑搭建框架。",
		en: "Worldbuilding is not about creating a map, but about building a framework for believable cause and effect.",
		ja: "ワールドビルディングとは地図を作ることではなく、信頼できる因果関係の枠組みを構築することである。",
		author: "肯·罗尔斯顿（Ken Rolston）",
		source: "《上古卷轴III：晨风》",
	},
	{
		zh: "游戏开发者最重要的技能不是编程也不是美术——而是对玩家的同理心。",
		en: "The most important skill for a game developer is not programming or art — it's empathy for the player.",
		ja: "ゲーム開発者に最も重要なスキルはプログラミングでもアートでもない。プレイヤーへの共感力だ。",
		author: "兰迪·史密斯（Randy Smith）",
		source: "《耻辱》《神偷》",
	},
	{
		zh: "数据驱动设计：让数字告诉你什么在奏效，而不是让自负说了算。",
		en: "Data-driven design: let the numbers tell you what's working, not your ego.",
		ja: "データ駆動型デザイン：自分のエゴではなく、数字に何が機能しているかを語らせよ。",
		author: "阿基·耶尔维宁（Aki Järvinen）",
		source: "游戏数据分析",
	},
	{
		zh: "伟大的游戏让玩家觉得自己是个天才——只因为发现了你一直想让他们做的事。",
		en: "Great games make the player feel like a genius — for discovering what you wanted them to do all along.",
		ja: "優れたゲームは、あなたがずっと彼らにやってほしかったことを発見したことで、プレイヤーを天才のように感じさせる。",
		author: "佚名",
		source: "游戏设计通用",
	},
	{
		zh: "打磨不是一个阶段，而是从第一天就开始的心态。",
		en: "Polish isn't a phase. It's a mindset you have from day one.",
		ja: "ポリッシュはフェーズではない。初日から持つべきマインドセットだ。",
		author: "凯尔·加布勒（Kyle Gabler）",
		source: "《粘粘世界》",
	},
	{
		zh: "游戏开发中最危险的四个字是\u201C以后再说\u201D。",
		en: "The four most dangerous words in game development are 'we'll fix it later'.",
		ja: "ゲーム開発で最も危険な四文字は「後で直す」である。",
		author: "改编自 德怀特·艾森豪威尔",
		source: "游戏项目管理",
	},
	{
		zh: "每个游戏机制都应为核心体验服务。如果不服务，就砍掉它。",
		en: "Every game mechanic should serve the core experience. If it doesn't, cut it.",
		ja: "すべてのゲームメカニクスは核となる体験に奉仕すべきである。そうでなければ、削除せよ。",
		author: "罗宾·亨尼克（Robin Hunicke）",
		source: "《风之旅人》/ MDA 框架",
	},
	{
		zh: "MDA 框架告诉我们：机制创造动态，动态创造美学体验。",
		en: "The MDA framework tells us: mechanics create dynamics, dynamics create aesthetic experiences.",
		ja: "MDAフレームワーク：メカニクスがダイナミクスを生み、ダイナミクスが美的体験を創り出す。",
		author: "亨尼克、勒布朗、祖贝克",
		source: "MDA: A Formal Approach to Game Design",
	},
	{
		zh: "失败不是乐趣的反面。它是乐趣不可或缺的原料。",
		en: "Failure is not the opposite of fun. It's an essential ingredient of fun.",
		ja: "失敗は楽しさの反対ではない。楽しさに不可欠な要素である。",
		author: "杰斯珀·尤尔（Jesper Juul）",
		source: "《失败的艺术》",
	},
	{
		zh: "如果你想做出一款好游戏，先玩好游戏。然后问自己它们为什么好。",
		en: "If you want to make a great game, play great games first. Then ask yourself why they're great.",
		ja: "良いゲームを作りたければ、まず優れたゲームを遊べ。そして、なぜそれが素晴らしいのかを自問せよ。",
		author: "小岛秀夫（Hideo Kojima）",
		source: "小岛秀夫",
	},
	{
		zh: "游戏写作不同于任何其他媒介——因为玩家就是主角。",
		en: "Game writing is different from any other medium — because the player is the protagonist.",
		ja: "ゲームのライティングは他のメディアとは根本的に異なる。プレイヤーこそが主人公だからだ。",
		author: "肯·莱文（Ken Levine）",
		source: "《生化奇兵》",
	},
	{
		zh: "核心循环是你游戏的心跳。其他一切都是装饰。",
		en: "The core loop is the heartbeat of your game. Everything else is decoration.",
		ja: "コアループはゲームの鼓動である。それ以外はすべて飾りに過ぎない。",
		author: "佚名",
		source: "游戏设计通用",
	},
	{
		zh: "平衡不是让一切平等，而是让每个选择在某种情境下都成立。",
		en: "Balance isn't about making everything equal, it's about making every choice viable in some context.",
		ja: "バランスとは全てを平等にすることではなく、あらゆる選択が何らかの状況で有効であることだ。",
		author: "索伦·约翰逊（Soren Johnson）",
		source: "《文明IV》《Offworld Trading Company》",
	},
	{
		zh: "一个原型抵得上一千份设计文档。",
		en: "A prototype is worth a thousand design documents.",
		ja: "一つのプロトタイプは千の設計書に値する。",
		author: "佚名",
		source: "游戏开发实践",
	},
	{
		zh: "最好的界面就是没有界面。最好的教程就是没有教程。",
		en: "The best interface is no interface. The best tutorial is no tutorial.",
		ja: "最高のインターフェースはインターフェースがないことだ。最高のチュートリアルはチュートリアルがないことだ。",
		author: "佚名",
		source: "交互设计原则",
	},
	{
		zh: "游戏是唯一一种让观众参与创造体验的艺术形式。",
		en: "Games are the only art form that lets the audience participate in creating the experience.",
		ja: "ゲームは、観客が体験の創造に参加できる唯一の芸術形式である。",
		author: "克里斯·克劳福德（Chris Crawford）",
		source: "《计算机游戏设计的艺术》",
	},
	{
		zh: "《矮人要塞》证明了深度永远胜过画面——只要你有一双能看见它的眼睛。",
		en: "Dwarf Fortress proves that depth always wins over graphics — as long as you have eyes to see it.",
		ja: "Dwarf Fortressは、深さが常にグラフィックに勝ることを証明している。それを見る目があればの話だが。",
		author: "塔恩·亚当斯（Tarn Adams）",
		source: "《矮人要塞》",
	},
	{
		zh: "程序化生成不是捷径，而是一种需要独特工艺的设计方式。",
		en: "Procedural generation isn't a shortcut. It's a design approach that requires its own craft.",
		ja: "プロシージャル生成は近道ではない。独自の技術を必要とする設計手法である。",
		author: "汤姆·贝茨（Tom Betts）",
		source: "程序化生成设计",
	},
	{
		zh: "设计文档不是为了记录你要建什么，而是为了发现你应该建什么。",
		en: "A design document isn't for recording what you're going to build. It's for discovering what you should build.",
		ja: "設計書は何を作るかを記録するためではなく、何を作るべきかを発見するためのものである。",
		author: "斯通·利布兰德（Stone Librande）",
		source: "《模拟城市》/ 一页设计文档法",
	},
	{
		zh: "一页设计迫使你分轻重缓急。如果一页都写不下，一个游戏也装不下。",
		en: "One-page design forces you to prioritize. If it can't fit on one page, it can't fit in one game.",
		ja: "1ページ設計は優先順位付けを強制する。1ページに収まらなければ、1つのゲームにも収まらない。",
		author: "斯通·利布兰德（Stone Librande）",
		source: "一页设计文档法",
	},
	{
		zh: "好游戏和伟大游戏的差距，往往只是把最后 5% 的打磨用在最关键的 5% 上。",
		en: "The difference between a good game and a great game is often spending the last 5% of polish on the most critical 5%.",
		ja: "良いゲームと偉大なゲームの差は、多くの場合、最後の5%のポリッシュを最も重要な5%に使うかどうかにある。",
		author: "佚名",
		source: "游戏开发通用",
	},
	{
		zh: "范围是独立游戏的无声杀手。从小做起，做完再做大。",
		en: "Scope is the silent killer of indie games. Start small, finish it, then go bigger.",
		ja: "スコープはインディーゲームの静かな殺し屋だ。小さく始めて、完成させてから大きくしろ。",
		author: "德里克·余（Derek Yu）",
		source: "《洞穴探险》",
	},
	{
		zh: "在程序化生成中，设计师从建筑师变成了园丁。",
		en: "In procedural generation, the designer goes from architect to gardener.",
		ja: "プロシージャル生成において、デザイナーは建築家から庭師になる。",
		author: "凯特·康普顿（Kate Compton）",
		source: "程序化生成 / PCG 研究",
	},
	{
		zh: "玩家能感觉到开发者对游戏有没有热情，他们像狗闻骨头一样闻得出来。",
		en: "Players can tell if the developer has passion for the game. They smell it like dogs smell fear.",
		ja: "プレイヤーは開発者がゲームに情熱を持っているかどうかを感じ取る。犬が恐怖を嗅ぎ分けるように。",
		author: "斯科特·罗杰斯（Scott Rogers）",
		source: "《Swatch! Level Up!》",
	},
	{
		zh: "你的头十款游戏会做得很烂，所以快点把它们做出来。",
		en: "Your first ten games will be terrible, so make them quickly.",
		ja: "最初の10本のゲームは酷いものになる。だから素早く作ってしまえ。",
		author: "杰西·谢尔（Jesse Schell）",
		source: "《游戏设计艺术》",
	},
	{
		zh: "痛苦会过去，但你的作品永远留存。",
		en: "Pain is temporary. Your work lives forever.",
		ja: "苦しみは一時的だが、作品は永遠に残る。",
		author: "约翰·卡马克（John Carmack）",
		source: "id Software 联合创始人",
	},
	{
		zh: "故事就像游戏的骨架，但它们不一定是游戏本身。游戏是关于做出选择的。",
		en: "Story is like the skeleton of a game, but it's not the game itself. Games are about making choices.",
		ja: "物語はゲームの骨格のようなものだが、ゲームそのものではない。ゲームとは選択をすることだ。",
		author: "沃伦·斯佩克特（Warren Spector）",
		source: "《杀出重围》",
	},
	{
		zh: "在故事中我们只能想象，在游戏中我们可以体验。这是交互性的核心力量。",
		en: "In stories we can only imagine. In games we can experience. This is the core power of interactivity.",
		ja: "物語では想像するしかできない。ゲームでは体験できる。これがインタラクティビティの核となる力である。",
		author: "埃尔亚达·莫斯（Elad Mordechai）/ 游戏编剧",
		source: "叙事设计",
	},
	{
		zh: "关卡设计的本质是创造有意义的空间。每个转角、每堵墙都应该能传递信息。",
		en: "Level design is about creating meaningful space. Every corner, every wall should communicate something.",
		ja: "レベルデザインとは意味のある空間を創造することだ。すべての角、すべての壁が何かを伝えるべきである。",
		author: "克里斯蒂安·沃克（Christian Walker）",
		source: "关卡设计通用",
	},
	{
		zh: "游戏这个词意味着竞争性，意味着你可以赢也可以输。",
		en: "The word 'game' implies competition — it means you can win or lose.",
		ja: "「ゲーム」という言葉は競争を意味する。勝つことも負けることもできるということだ。",
		author: "横井军平（Gunpei Yokoi）",
		source: "任天堂 / Game Boy 之父",
	},
	{
		zh: "侧向思考——枯萎技术的水平思考。",
		en: "Lateral thinking with withered technology.",
		ja: "枯れた技術の水平思考。",
		author: "横井军平（Gunpei Yokoi）",
		source: "任天堂 设计哲学",
	},
	{
		zh: "游戏设计师是让玩家快乐的人。",
		en: "A game designer is someone who makes people happy.",
		ja: "ゲームデザイナーとは、人を幸せにする仕事である。",
		author: "上田文人（Fumito Ueda）",
		source: "《旺达与巨像》《ICO》",
	},
	{
		zh: "我想创造没人见过的东西。不管做什么类型，我都想做独一无二的东西。",
		en: "I want to create something no one has ever seen. Whatever genre I'm working in, I want it to be unique.",
		ja: "誰も見たことのないものを作りたい。どんなジャンルであれ、唯一無二のものを作りたい。",
		author: "上田文人（Fumito Ueda）",
		source: "《旺达与巨像》",
	},
	{
		zh: "游戏需要简单才能触及非玩家群体。我自己也不喜欢太复杂的游戏。",
		en: "Games need to be simple to reach non-gamers. I don't like overly complex games myself.",
		ja: "ゲームはシンプルでなければ、ゲーマー以外には届かない。私自身、複雑すぎるゲームは好きではない。",
		author: "上田文人（Fumito Ueda）",
		source: "《ICO》设计理念",
	},
	{
		zh: "惊险和愉悦都不应该在游戏中占主导，好的游戏需要两者之间的平衡。",
		en: "Neither thrill nor pleasure should dominate a game. A good game needs a balance of both.",
		ja: "スリルも楽しさも、どちらかが支配的であってはならない。良いゲームには両方のバランスが必要だ。",
		author: "福光光司（Fukio Mitsuji）",
		source: "《泡泡龙》",
	},
	{
		zh: "只有游戏会回击玩家时，玩家才有动力继续。",
		en: "Only when a game fights back does the player have motivation to continue.",
		ja: "ゲームがプレイヤーに反撃してこそ、プレイヤーは続ける意欲を持つ。",
		author: "福光光司（Fukio Mitsuji）",
		source: "街机游戏设计",
	},
	{
		zh: "要想做出好游戏，你得有分析性的头脑，还要有从无到有创造新想法的想象力。",
		en: "To make good games, you need an analytical mind and the imagination to create new ideas from nothing.",
		ja: "良いゲームを作るには、分析的な頭脳と、ゼロから新しいアイデアを生み出す想像力の両方が必要だ。",
		author: "福光光司（Fukio Mitsuji）",
		source: "给游戏设计师的建议",
	},
	{
		zh: "每一个游戏都承诺了玩家与敌人之间的某种冲突，但如果敌人无视玩家'不跟他玩'呢？玩家肯定会因为无聊而离开。",
		en: "Every game promises a conflict between the player and an enemy. But if the enemy ignores the player's refusal to engage... the player will surely leave out of boredom.",
		ja: "すべてのゲームはプレイヤーと敵との衝突を約束する。しかし、敵がプレイヤーの拒否を無視したら？プレイヤーは退屈して去っていくだろう。",
		author: "福光光司（Fukio Mitsuji）",
		source: "《Bubble Bobble》设计",
	},
	{
		zh: "从菜鸟到专业游戏程序员没有捷径。至少需要2-3年，通常需要5-10年。",
		en: "There is no shortcut from a novice to a professional game programmer. It takes at least 2-3 years, often 5-10 years.",
		ja: "初心者からプロのゲームプログラマーへの近道はない。最低でも2〜3年、通常は5〜10年かかる。",
		author: "安迪·加文（Andy Gavin）",
		source: "Naughty Dog / 《古惑狼》",
	},
	{
		zh: "每一堆箱子、每一组敌人都被精心放置，为的是构建游戏节奏的脉搏。",
		en: "Every stack of crates, every enemy placement was carefully positioned to build the game's pacing pulse.",
		ja: "すべての箱の山、すべての敵の配置は、ゲームのペースを構築するために注意深く置かれている。",
		author: "安迪·加文（Andy Gavin）",
		source: "《古惑狼》关卡设计",
	},
	{
		zh: "游戏的叙事不需要像电影那样层层揭开真相。游戏的魅力在于你'去做'，而不是'去看'。",
		en: "Game narrative doesn't need to reveal truth layer by layer like a film. The beauty of games is that you DO, not that you WATCH.",
		ja: "ゲームの物語は映画のように真実を段階的に明かす必要はない。ゲームの魅力は「見ること」ではなく「行うこと」にある。",
		author: "上田文人（Fumito Ueda）",
		source: "《ICO》《旺达与巨像》",
	},
	{
		zh: "原型化、原型化、再原型化。不要在花里胡哨的设计文档上浪费时间。",
		en: "Prototype, prototype, prototype. Don't waste time on fancy design documents.",
		ja: "プロトタイプ、プロトタイプ、プロトタイプ。派手な設計書に時間を無駄にするな。",
		author: "肯·王（Ken Wong）",
		source: "《纪念碑谷》",
	},
	{
		zh: "失败是设计过程中必不可少的一部分。每次失败都在教你什么东西不该做。",
		en: "Failure is an essential part of the design process. Every failure teaches you what not to do.",
		ja: "失敗は設計プロセスに不可欠な一部である。失敗は何をすべきでないかを教えてくれる。",
		author: "彼得·莫利纽克斯（Peter Molyneux）",
		source: "《黑与白》《神鬼寓言》",
	},
	{
		zh: "如果你想让游戏看起来容易，你自己得先做得很辛苦。",
		en: "If you want your game to look easy, you have to work hard at it first.",
		ja: "ゲームを簡単に見せたければ、まず自分が苦労して作らなければならない。",
		author: "宫本茂（Shigeru Miyamoto）",
		source: "任天堂",
	},
	{
		zh: "一个好游戏应该是容易上手难以精通的。",
		en: "A good game should be easy to pick up but hard to master.",
		ja: "良いゲームは簡単に始められて、奥が深いものだ。",
		author: "宫本茂（Shigeru Miyamoto）",
		source: "任天堂 设计原则",
	},
	{
		zh: "我不做游戏给玩家，我做游戏给人们。",
		en: "I don't make games for players. I make games for people.",
		ja: "私はプレイヤーのためにゲームを作るのではない。人のためにゲームを作るのだ。",
		author: "宫本茂（Shigeru Miyamoto）",
		source: "任天堂",
	},
	{
		zh: "故事不是游戏的本质。玩家在游戏中做的事才是。",
		en: "The story is not the essence of a game. What the player does in the game is.",
		ja: "物語はゲームの本質ではない。プレイヤーがゲームの中で何をするかが本質である。",
		author: "小岛秀夫（Hideo Kojima）",
		source: "《潜龙谍影》系列",
	},
	{
		zh: "交互性是游戏独有的语言。其他媒介能展示勇气，但只有游戏能让玩家成为勇敢的人。",
		en: "Interactivity is the unique language of games. Other media can show courage, but only games can make the player BECOME courageous.",
		ja: "インタラクティビティはゲーム独自の言語である。他のメディアは勇気を「見せる」ことはできても、プレイヤー自身を勇敢にできるのはゲームだけだ。",
		author: "大卫·贾菲（David Jaffe）",
		source: "《战神》",
	},
	{
		zh: "一个关卡应该像一本好书一样有开头、中间和结尾。",
		en: "A level should have a beginning, middle, and end like a good book.",
		ja: "レベルには良書のような序章、展開、結末があるべきだ。",
		author: "理查德·巴特利特（Richard Bartle）",
		source: "MUD / 玩家类型理论",
	},
	{
		zh: "程序设计之于游戏开发，就像语法之于写作。没有它你什么都做不了，但光有它也写不出杰作。",
		en: "Programming is to game development what grammar is to writing. You can't do anything without it, but it alone can't write a masterpiece.",
		ja: "プログラミングはゲーム開発にとって、文法が文章作成にとってそうであるようなものだ。それがなければ何もできないが、それだけでは名作は書けない。",
		author: "约翰·卡马克（John Carmack）",
		source: "id Software",
	},
	{
		zh: "在任天堂，我们不是在制造游戏，我们是在制造玩具。玩具的本质是好玩。",
		en: "At Nintendo, we're not making games. We're making toys. And toys are about fun.",
		ja: "任天堂では、ゲームを作っているのではない。玩具を作っているのだ。玩具の本質は楽しさにある。",
		author: "宫本茂（Shigeru Miyamoto）",
		source: "任天堂",
	},
	{
		zh: "AI 不是用来替代游戏设计师的，而是用来放大设计师的创造力的。",
		en: "AI is not here to replace game designers. It's here to amplify their creativity.",
		ja: "AIはゲームデザイナーを置き換えるものではなく、その創造性を増幅するためにある。",
		author: "朱利安·图维尔（Julian Togelius）",
		source: "AI 游戏设计研究",
	},
	{
		zh: "玩家的时间是最宝贵的资源。你的游戏不配浪费它。",
		en: "A player's time is the most valuable resource. Your game isn't worth wasting it.",
		ja: "プレイヤーの時間は最も貴重なリソースである。あなたのゲームはそれを無駄にする価値などない。",
		author: "拉夫·科斯特（Raph Koster）",
		source: "《游戏设计的乐趣理论》",
	},
	{
		zh: "最好的游戏教你如何玩，而不让你意识到你在学习。",
		en: "The best games teach you how to play without you realizing you're learning.",
		ja: "最高のゲームは、学んでいることに気付かせずに遊び方を教えてくれる。",
		author: "席德·梅尔（Sid Meier）",
		source: "《文明》系列",
	},
	{
		zh: "在游戏中，规则就是一切。改变规则，你就改变了游戏本身。",
		en: "In games, rules are everything. Change the rules, and you've changed the game itself.",
		ja: "ゲームにおいて、ルールが全てである。ルールを変えれば、ゲームそのものが変わる。",
		author: "伯尼·德科文（Bernie DeKoven）",
		source: "《The Well-Played Game》",
	},
	{
		zh: "好的游戏写作不是写漂亮的句子，而是设计玩家能发现的情境。",
		en: "Good game writing isn't about writing beautiful sentences. It's about designing situations the player can discover.",
		ja: "優れたゲームライティングとは美しい文章を書くことではない。プレイヤーが発見できる状況を設計することである。",
		author: "苏珊·奥康纳（Susan O'Connor）",
		source: "游戏叙事设计 / 《神秘海域》",
	},
	{
		zh: "关卡是无声的故事讲述者。好的关卡通过空间和光线来说话。",
		en: "A level is a silent storyteller. Good levels speak through space and light.",
		ja: "レベルは沈黙の語り部である。良いレベルは空間と光で語る。",
		author: "史蒂夫·盖诺（Steve Gaynor）",
		source: "《Gone Home》关卡设计",
	},
	{
		zh: "游戏机制是动词，叙事是名词。动词让名词变得重要。",
		en: "Game mechanics are verbs. Narrative is nouns. Verbs make nouns matter.",
		ja: "ゲームメカニクスは動詞であり、ナラティブは名詞である。動詞が名詞を意味あるものにする。",
		author: "塔尔·桑格（Tadhg Kelly）",
		source: "游戏设计理论",
	},
	{
		zh: "当你把有趣的选择放在玩家面前，你就不需要强制他们'做正确的事'。正确的选择自然会吸引人。",
		en: "When you put interesting choices in front of the player, you don't need to force them to 'do the right thing'. The right choice naturally attracts them.",
		ja: "プレイヤーの前に興味深い選択を置けば、「正しいことをさせる」必要はない。正しい選択は自然と彼らを引き付ける。",
		author: "丹·费尔德（Dan Felder）",
		source: "游戏设计博客",
	},
	{
		zh: "你不必制作所有人都喜欢的游戏。你只需要制作一些人非常热爱的游戏。",
		en: "You don't need to make a game that everyone loves. You just need to make a game that some people love very much.",
		ja: "すべての人に愛されるゲームを作る必要はない。一部の人に非常に愛されるゲームを作ればいいのだ。",
		author: "富兰克·拉兹（Frank Lantz）",
		source: "NYU 游戏中心教授",
	},
	{
		zh: "游戏设计最难的技能不是加法而是减法——知道该去掉什么。",
		en: "The hardest skill in game design is not addition but subtraction — knowing what to remove.",
		ja: "ゲームデザインで最も難しいスキルは足し算ではなく引き算である。何を削除すべきかを知ることだ。",
		author: "布伦达·罗梅罗（Brenda Romero）",
		source: "游戏设计师 / 教授",
	},
	{
		zh: "真正的开放世界不是地图大，而是玩家解决问题的方式多。",
		en: "True open world isn't about map size. It's about how many ways the player can solve a problem.",
		ja: "真のオープンワールドとはマップの広さではない。プレイヤーが問題を解決する方法の多さである。",
		author: "肯·莱文（Ken Levine）",
		source: "《生化奇兵》",
	},
	{
		zh: "像素级的打磨，比听起来重要得多。玩家可能说不清哪里不对，但他们能感觉到。",
		en: "Pixel-perfect polish matters far more than it sounds like it does. Players may not be able to say what's wrong, but they can feel it.",
		ja: "ピクセル単位のポリッシュは、聞こえ以上に重要である。プレイヤーは何が間違っているかを言葉にできなくても、感じ取ることができる。",
		author: "埃德蒙·麦克米伦（Edmund McMillen）",
		source: "《以撒的结合》《超级肉肉哥》",
	},
	{
		zh: "最好的游戏测试玩家能找出你觉得没人会在意的问题。多留意他们。",
		en: "Playtest with players who will find problems you didn't think anyone would notice. Pay attention to them.",
		ja: "誰も気にしないと思っていた問題を見つけてくれるプレイヤーとプレイテストをしろ。彼らに注意を払え。",
		author: "迈克·安布勒（Mike Ambinder）",
		source: "Valve 游戏测试 / 心理学",
	},
	{
		zh: "在游戏的尽头，玩家不会记得你写的故事——他们会记得他们自己的故事。",
		en: "At the end of a game, players won't remember the story you wrote — they'll remember their own story.",
		ja: "ゲームの終わりに、プレイヤーはあなたが書いた物語を覚えてはいない。彼ら自身の物語を覚えているのだ。",
		author: "克林特·霍金（Clint Hocking）",
		source: "《孤岛惊魂2》创意总监",
	},
	{
		zh: "好游戏的秘密不是没有Bug，而是玩家在Bug出现时也不在乎。",
		en: "The secret of good games isn't no bugs. It's that players don't care about the bugs.",
		ja: "良いゲームの秘密はバグがないことではない。プレイヤーがバグを気にしないことだ。",
		author: "汤姆·霍尔（Tom Hall）",
		source: "《Commander Keen》共同创作者",
	},
	{
		zh: "设计文档不是蓝图，而是交谈的起点。",
		en: "A design document isn't a blueprint. It's a starting point for conversation.",
		ja: "設計書は設計図ではない。対話の出発点である。",
		author: "斯通·利布兰德（Stone Librande）",
		source: "《暗黑破坏神3》/ 一页设计文档法",
	},
	{
		zh: "关卡设计的第一步不是打开编辑器，而是画草图。",
		en: "The first step of level design isn't opening the editor. It's sketching.",
		ja: "レベルデザインの第一歩はエディタを開くことではない。スケッチを描くことだ。",
		author: "约翰·罗梅罗（John Romero）",
		source: "《DOOM》关卡设计",
	},
	{
		zh: "当玩家说'这个游戏太简单了'，通常不是因为难度低，而是因为选择太少。",
		en: "When a player says 'this game is too easy', it's usually not about difficulty — it's about having too few choices.",
		ja: "プレイヤーが「このゲームは簡単すぎる」と言うとき、それは難易度ではなく、選択肢が少なすぎることが原因である。",
		author: "索伦·约翰逊（Soren Johnson）",
		source: "《文明IV》主设计师",
	},
	{
		zh: "世界观和故事给玩家一个'为什么'。没有这个'为什么'，再好的机制也会让人觉得空洞。",
		en: "Worldbuilding and story give the player a 'why'. Without that 'why', even the best mechanics feel hollow.",
		ja: "ワールドビルディングと物語はプレイヤーに「なぜ」を与える。その「なぜ」がなければ、どんなに優れたメカニクスも空虚に感じられる。",
		author: "帕特里斯·德西莱（Patrice Désilets）",
		source: "《刺客信条》创意总监",
	},
	{
		zh: "开放世界的真正挑战不是内容量，而是密度——每个角落都得有故事可讲。",
		en: "The real challenge of open world isn't content volume, it's density — every corner needs a story to tell.",
		ja: "オープンワールドの真の挑戦はコンテンツ量ではなく、密度である。すべての隅に語るべき物語が必要だ。",
		author: "托德·霍华德（Todd Howard）",
		source: "Bethesda Game Studios",
	},
	{
		zh: "最好的叙事设计是你甚至没注意到它在发生。故事和玩法融为一体，不分彼此。",
		en: "The best narrative design is the kind you don't even notice happening. Story and gameplay become inseparable.",
		ja: "最高のナラティブデザインは、その存在にすら気付かないものだ。物語とゲームプレイが不可分になる。",
		author: "詹姆斯·沃格特（James Vogt）",
		source: "游戏叙事设计",
	},
	{
		zh: "一个被完全理解的游戏是很快就会被放弃的游戏。神秘感也是一种驱动力。",
		en: "A completely understood game is a game that will quickly be abandoned. Mystery is also a driving force.",
		ja: "完全に理解されたゲームは、すぐに放棄されるゲームである。神秘性もまた原動力である。",
		author: "拉夫·科斯特（Raph Koster）",
		source: "《游戏设计的乐趣理论》",
	},
	{
		zh: "读游戏设计文档不如玩一个原型。玩一个原型不如让一个陌生人试玩。",
		en: "Reading a design document is not as good as playing a prototype. Playing a prototype is not as good as watching a stranger playtest it.",
		ja: "設計書を読むよりもプロトタイプを遊ぶ方が良い。プロトタイプを遊ぶよりも、見知らぬ人がそれをプレイテストするのを見る方が良い。",
		author: "本·弗莱（Ben Fry）",
		source: "交互设计 / 原型化方法",
	},
];
