import type { NewsSource } from "../utils/types";

/**
 * 游戏开发工具/资源链接源（静态数据，无 RSS 抓取）
 * 按分类展示，帮助用户发现有用的开发站点
 */

interface LinkEntry {
	id: string;
	title: string;
	url: string;
	category: string;
	lang: string;
	desc?: string;
}

const links: LinkEntry[] = [
	/* ===== 开发社区 ===== */
	{
		id: "link-gamedevnet",
		title: "GameDev.net",
		url: "https://gamedev.net/",
		category: "开发社区",
		lang: "en",
		desc: "老牌游戏开发者社区，活跃论坛/技术文章/博客/资源分享",
	},
	{
		id: "link-tigsource",
		title: "TIGSource",
		url: "https://www.tigsource.com/",
		category: "开发社区",
		lang: "en",
		desc: "经典独立游戏论坛，开发者发布 Devlog 与开发讨论的首选地之一",
	},
	{
		id: "link-gh-learn-gamedev",
		title: "awesome-learn-gamedev (dawdle-deer)",
		url: "https://github.com/dawdle-deer/awesome-learn-gamedev",
		category: "开发社区",
		lang: "en",
		desc: "游戏开发学习资源导航，从零开始的系统学习路径",
	},
	{
		id: "link-gamedev-discord",
		title: "Game Dev League",
		url: "https://discord.gg/gamedev",
		category: "开发社区",
		lang: "en",
		desc: "Discord 上最大的游戏开发者社群，按引擎/工种分频道讨论",
	},
	{
		id: "link-itchio",
		title: "itch.io",
		url: "https://itch.io/",
		category: "开发社区",
		lang: "en",
		desc: "最大的独立游戏发布与素材交易平台，海量免费/付费游戏和开发资源",
	},
	{
		id: "link-devtogamedev",
		title: "dev.to #gamedev",
		url: "https://dev.to/t/gamedev",
		category: "开发社区",
		lang: "en",
		desc: "开发者社区 dev.to 上的游戏开发标签，每日有大量实战经验分享与讨论",
	},
	{
		id: "link-godotshaders",
		title: "Godot Shaders",
		url: "https://godotshaders.com/",
		category: "开发社区",
		lang: "en",
		desc: "Godot 着色器分享社区，WebGL 实时预览+源码下载，适合学习着色器编程",
	},
	{
		id: "link-mastodon-gamedev",
		title: "GameDev Mastodon",
		url: "https://mastodon.gamedev.place/",
		category: "开发社区",
		lang: "en",
		desc: "游戏开发者 Mastodon 实例，去中心化社交网络上的活跃开发者社区",
	},
	{
		id: "link-gameres",
		title: "GameRes 游资网",
		url: "https://www.gameres.com/",
		category: "开发社区",
		lang: "zh",
		desc: "国内知名游戏开发社区，原创教程/资源/问答（网络受限）",
	},

	{
		id: "link-juejin-game",
		title: "掘金 游戏开发",
		url: "https://juejin.cn/tag/%E6%B8%B8%E6%88%8F%E5%BC%80%E5%8F%91",
		category: "开发社区",
		lang: "zh",
		desc: "掘金技术社区游戏开发标签，国内开发者实战文章（网络受限）",
	},
	{
		id: "link-sf-game",
		title: "SegmentFault 游戏开发",
		url: "https://segmentfault.com/t/%E6%B8%B8%E6%88%8F%E5%BC%80%E5%8F%91",
		category: "开发社区",
		lang: "zh",
		desc: "SegmentFault 技术社区游戏开发问答/文章（网络受限）",
	},
	{
		id: "link-cnblogs-game",
		title: "博客园 游戏开发",
		url: "https://www.cnblogs.com/cate/gamedev/",
		category: "开发社区",
		lang: "zh",
		desc: "博客园游戏开发分类，国内程序员的开发经验分享（网络受限）",
	},

	/* ===== 游戏设计 ===== */
	{
		id: "link-gamedesignskills",
		title: "Game Design Skills",
		url: "https://gamedesignskills.com/blog/",
		category: "游戏设计",
		lang: "en",
		desc: "游戏设计百科/文章站，涵盖系统设计/关卡设计/战斗设计/职业发展等主题",
	},
	{
		id: "link-altf4",
		title: "Alt-F4",
		url: "https://alt-f4.blog/zh/",
		category: "游戏设计",
		lang: "zh",
		desc: "Factorio 技术/Mod 分析博客中文版，自动化游戏设计与性能优化深度文章",
	},
	{
		id: "link-rimworld",
		title: "RimWorld",
		url: "https://rimworldgame.com/",
		category: "游戏设计",
		lang: "en",
		desc: "RimWorld 官方开发站，殖民模拟类游戏设计参考（与 Ludeon Studios 互补）",
	},
	{
		id: "link-gh-awesome-game-design",
		title: "awesome-game-design (rafaskb)",
		url: "https://github.com/rafaskb/awesome-game-design",
		category: "游戏设计",
		lang: "en",
		desc: "游戏设计资源合集，设计模式/关卡/UX/叙事等分类",
	},
	{
		id: "link-deepfriedgamer",
		title: "DeepFriedGamer",
		url: "https://deepfriedgamer.com/",
		category: "游戏设计",
		lang: "en",
		desc: "游戏设计理论博客+播客，从基础原理到高级实战的系统化设计讨论",
	},
	{
		id: "link-gamedesignguide",
		title: "Game Design Guide (Substack)",
		url: "https://gamedesignguide.substack.com/",
		category: "游戏设计",
		lang: "en",
		desc: "游戏设计与开发参考指南通讯，涵盖系统设计/原型/迭代方法（Substack 域名受限）",
	},
	{
		id: "link-justingary",
		title: "Think Like A Game Designer",
		url: "https://justingarydesign.substack.com/",
		category: "游戏设计",
		lang: "en",
		desc: "桌游设计师 Justin Gary 的设计思考通讯+播客，每期深度剖析设计方法论（Substack 域名受限）",
	},
	{
		id: "link-videogameworkshop",
		title: "Video Game Workshop",
		url: "https://videogameworkshop.substack.com/",
		category: "游戏设计",
		lang: "en",
		desc: "任天堂风格关卡设计方法论分析，以实际游戏案例拆解关卡设计核心原理（Substack 域名受限）",
	},
	{
		id: "link-scottfine",
		title: "Scott Fine Game Design",
		url: "https://scottfinegamedesign.com/",
		category: "游戏设计",
		lang: "en",
		desc: "游戏设计分析博客，深度拆解 RPG 升级系统/战斗机制/技能设计",
	},
	{
		id: "link-gamescrye",
		title: "GameScrye",
		url: "https://gamescrye.com/",
		category: "游戏设计",
		lang: "en",
		desc: "游戏设计与叙事设计博客，探讨玩家如何沉浸于交互故事的工艺",
	},
	{
		id: "link-gamedesignlevels",
		title: "Game Design Levels (Substack)",
		url: "https://jaimetous.substack.com/",
		category: "游戏设计",
		lang: "en",
		desc: "关卡设计与系统一致性分析，探讨游戏不同系统如何协同工作（Substack 域名受限）",
	},

	/* ===== 视频/频道 ===== */
	{
		id: "link-yt-gameoveranalyser",
		title: "Game Overanalyser",
		url: "https://www.youtube.com/@GameOveranalyser",
		category: "视频/频道",
		lang: "en",
		desc: "游戏设计分析频道，以独特视角拆解经典与现代游戏的设计逻辑",
	},

	/* ===== 开发社区 ===== */
	{
		id: "link-bili-indienova",
		title: "indienova B站频道",
		url: "https://space.bilibili.com/25676644",
		category: "视频/频道",
		lang: "zh",
		desc: "indienova 独立游戏官方 B 站账号，分享独立游戏开发/设计视频内容",
	},

	/* ===== 开发社区 ===== */
	{
		id: "link-numeric-planner",
		title: "游戏数值策划完全教程",
		url: "https://zsc.github.io/numeric_planner_tutorial/",
		category: "游戏设计",
		lang: "zh",
		desc: "GitHub Pages 上的数值策划/经济系统开放教程，从街机到大型游戏的数值设计",
	},

	/* ===== 开发社区 ===== */
	{
		id: "link-gamedeveloper",
		title: "Game Developer",
		url: "https://www.gamedeveloper.com/",
		category: "开发社区",
		lang: "en",
		desc: "原 Gamasutra，游戏行业深度分析与技术文章，覆盖面最广的行业媒体（部分网络受限）",
	},

	/* ===== 发行/运营 ===== */
	{
		id: "link-gameassemly",
		title: "Game Dev Assembly (Substack)",
		url: "https://gamedevnewsletter.substack.com/",
		category: "游戏设计",
		lang: "en",
		desc: "游戏开发营销/商业策略通讯，覆盖发行/增长/全球化等实务话题（Substack 域名受限）",
	},

	/* ===== 编程 & 架构 ===== */
	{
		id: "link-gp-patterns",
		title: "Game Programming Patterns",
		url: "https://gameprogrammingpatterns.com/",
		category: "编程 & 架构",
		lang: "en",
		desc: "游戏编程设计模式在线全书，涵盖命令/观察者/对象池/状态机等经典模式",
	},
	{
		id: "link-generalistprogrammer",
		title: "Generalist Programmer",
		url: "https://generalistprogrammer.com/",
		category: "编程 & 架构",
		lang: "en",
		desc: "游戏开发编程教程站，涵盖 Unity/Unreal/C#/C++ 及游戏设计模式",
	},
	{
		id: "link-lazyfoo",
		title: "Lazy Foo' SDL",
		url: "https://lazyfoo.net/",
		category: "编程 & 架构",
		lang: "en",
		desc: "SDL 2D 游戏编程入门教程，从窗口创建到粒子系统，完整 C++ 指南",
	},

	/* ===== 编程 & 架构 ===== */
	{
		id: "link-learnopengl",
		title: "Learn OpenGL",
		url: "https://learnopengl.com/",
		category: "编程 & 架构",
		lang: "en",
		desc: "现代 OpenGL 图形编程入门教程，从 shader 到 PBR 渲染一应俱全",
	},
	{
		id: "link-pikuma",
		title: "Pikuma",
		url: "https://pikuma.com/",
		category: "编程 & 架构",
		lang: "en",
		desc: "游戏数学/物理/图形学底层原理教程，从零实现软渲染器和游戏引擎",
	},

	/* ===== 编程 & 架构 ===== */
	{
		id: "link-pcgwiki",
		title: "PCG Wiki",
		url: "https://pcg.wikidot.com/",
		category: "编程 & 架构",
		lang: "en",
		desc: "程序化生成 Wiki，算法分类+游戏目录+学术资源索引，PCG 领域最全知识库",
	},

	/* ===== 游戏设计 ===== */
	{
		id: "link-ink",
		title: "Ink (inkle)",
		url: "https://www.inklestudios.com/ink/",
		category: "游戏设计",
		lang: "en",
		desc: "开源叙事脚本语言，被 80 Days / Heaven's Vault 等大量独立游戏使用",
	},
	{
		id: "link-yarnspinner",
		title: "Yarn Spinner",
		url: "https://yarnspinner.dev/",
		category: "游戏设计",
		lang: "en",
		desc: "对话系统工具，VS Code 编辑器+语法高亮+预览，集成 Unity/Godot",
	},
	{
		id: "link-twine",
		title: "Twine",
		url: "https://twinery.org/",
		category: "游戏设计",
		lang: "en",
		desc: "开源非线性叙事/互动小说创作工具，可视化分支故事编辑器",
	},
	{
		id: "link-storyflow-editor",
		title: "StoryFlow Editor",
		url: "https://storyflow-editor.com/",
		category: "游戏设计",
		lang: "en",
		desc: "节点式对话编辑器，支持 Unity/Unreal/Godot，开源 MIT 许可",
	},
	{
		id: "link-narrativedesigner",
		title: "NarrativeDesigner.com",
		url: "https://www.narrativedesigner.com/",
		category: "游戏设计",
		lang: "en",
		desc: "叙事设计全流程参考站，从大纲到对话树的方法论与模板",
	},
	{
		id: "link-narrativenews",
		title: "Narrative News (Substack)",
		url: "https://narrativenews.substack.com/",
		category: "游戏设计",
		lang: "en",
		desc: "游戏叙事设计月报，汇总资源/职位/活动/访谈（Substack 域名受限）",
	},
	{
		id: "link-narrativedesign-substack",
		title: "Narrative Design (Substack)",
		url: "https://narrativedesign.substack.com/",
		category: "游戏设计",
		lang: "en",
		desc: "游戏叙事设计深度分析，从 Chrono Trigger 到现代分支叙事的演变（Substack 域名受限）",
	},
	{
		id: "link-pietronarrative",
		title: "Around Narrative Design (Substack)",
		url: "https://peterpunk.substack.com/",
		category: "游戏设计",
		lang: "en",
		desc: "Pietro Polsinelli 的叙事设计研究，涵盖视频/桌游/应用游戏叙事（Substack 域名受限）",
	},

	/* ===== 游戏设计 ===== */
	{
		id: "link-leveldesignorg",
		title: "LEVEL-DESIGN.org",
		url: "https://level-design.org/",
		category: "游戏设计",
		lang: "en",
		desc: "500+ 游戏关卡截图参考数据库，按游戏/类型检索关卡布局与结构",
	},
	{
		id: "link-worldofleveldesign",
		title: "World of Level Design",
		url: "https://www.worldofleveldesign.com/",
		category: "游戏设计",
		lang: "en",
		desc: "UE/Unity/Blender 关卡设计实战教程，涵盖光效/地形/性能优化",
	},
	{
		id: "link-leveldesignbook-cn",
		title: "关卡设计指南（中文版）",
		url: "https://book.leveldesignbook.cn/",
		category: "游戏设计",
		lang: "zh",
		desc: "《The Level Design Book》中文译本，涵盖关卡制作全流程与经验分享",
	},

	/* ===== 游戏设计 ===== */
	{
		id: "link-chapterpub-worldbuilding",
		title: "Chapter Pub 世界观指南",
		url: "https://blog.chapter.pub/",
		category: "游戏设计",
		lang: "en",
		desc: "世界观创作完整指南，涵盖地理/文化/魔法/政治/历史的系统化构建",
	},
	{
		id: "link-savameta",
		title: "Sava Meta",
		url: "https://savameta.com/",
		category: "游戏设计",
		lang: "en",
		desc: "游戏叙事与世界观设计博客，探讨故事如何在交互媒介中发挥作用",
	},

	/* ===== UI/UX 设计 ===== */
	{
		id: "link-gameuidatabase",
		title: "Game UI Database",
		url: "https://www.gameuidatabase.com/",
		category: "UI/UX 设计",
		lang: "en",
		desc: "1800+ 游戏、73000+ 截图 UI 参考库，按屏幕类型/交互模式检索",
	},
	{
		id: "link-padcrafter",
		title: "PadCrafter",
		url: "https://www.padcrafter.com/",
		category: "UI/UX 设计",
		lang: "en",
		desc: "手柄/键盘按键布局在线设计工具，适合游戏 UI 原型",
	},

	/* ===== 游戏引擎 ===== */
	/* ===== 游戏引擎 ===== */
	{
		id: "link-monogame",
		title: "MonoGame",
		url: "https://www.monogame.net/",
		category: "游戏引擎",
		lang: "en",
		desc: "跨平台 .NET 游戏框架，Stardew Valley / Celeste 等名作的技术底座",
	},
	{
		id: "link-gh-awesome-game-engines",
		title: "awesome-game-engines (brandonhimpfen)",
		url: "https://github.com/brandonhimpfen/awesome-game-engines",
		category: "游戏引擎",
		lang: "en",
		desc: "游戏引擎/框架汇总列表，覆盖 2D/3D/VR",
	},
	{
		id: "link-fyrox",
		title: "Fyrox",
		url: "https://fyrox.rs/",
		category: "游戏引擎",
		lang: "en",
		desc: "Rust 开源 3D 游戏引擎，功能完整的现代引擎",
	},
	{
		id: "link-gdevelop",
		title: "GDevelop 中文",
		url: "https://gdevelop.io/zh-cn/",
		category: "游戏引擎",
		lang: "zh",
		desc: "开源零代码游戏引擎，支持 2D/3D，AI 辅助开发，适合快速原型和教学",
	},
	{
		id: "link-unrealengine",
		title: "Unreal Engine",
		url: "https://www.unrealengine.com/",
		category: "游戏引擎",
		lang: "en",
		desc: "Epic Games 开发的 AAA 级 3D 引擎，C++/蓝图双模式，影视虚拟制片首选",
	},
	{
		id: "link-unrealengine-cn",
		title: "Unreal Engine 中文站",
		url: "https://www.unrealengine.com/zh-CN/",
		category: "游戏引擎",
		lang: "zh",
		desc: "虚幻引擎中文官方站点，含中文文档/案例/社区",
	},
	{
		id: "link-unrealsource",
		title: "UnrealSource",
		url: "https://unrealsource.com/",
		category: "游戏引擎",
		lang: "en",
		desc: "Unreal Engine 独立新闻通讯，每期汇总引擎更新/插件/技巧",
	},
	{
		id: "link-unity",
		title: "Unity",
		url: "https://unity.com/",
		category: "游戏引擎",
		lang: "en",
		desc: "全球最普及的 2D/3D 游戏引擎，C# 语言，移动端开发绝对主力",
	},
	{
		id: "link-unity-cn",
		title: "Unity 中文官网",
		url: "https://unity.cn/",
		category: "游戏引擎",
		lang: "zh",
		desc: "Unity 中国官方站，含中文学习资源/社区/案例",
	},
	{
		id: "link-godot",
		title: "Godot Engine",
		url: "https://godotengine.org/",
		category: "游戏引擎",
		lang: "en",
		desc: "MIT 开源 2D/3D 游戏引擎，节点化架构+GDScript/C#/C++ 多语言",
	},
	{
		id: "link-godot-cn",
		title: "Godot 中国站",
		url: "https://www.godot-cn.com/",
		category: "游戏引擎",
		lang: "zh",
		desc: "Godot 中文社区站点，中文文档翻译/教程/问答",
	},
	{
		id: "link-godothub",
		title: "GodotHub",
		url: "https://godothub.com/",
		category: "游戏引擎",
		lang: "zh",
		desc: "国内 Godot 游戏引擎社区服务平台，教程/资源/问答",
	},
	{
		id: "link-godotfoundry",
		title: "Godot Foundry",
		url: "https://godotfoundry.com/",
		category: "游戏引擎",
		lang: "en",
		desc: "Godot 引擎教程站，含着色器分解/GDScript 教程/资源指南",
	},
	{
		id: "link-defold",
		title: "Defold",
		url: "https://defold.com/",
		category: "游戏引擎",
		lang: "en",
		desc: "跨平台 2D 游戏引擎，Lua 脚本，轻量快速，King（糖果粉碎）出品",
	},
	{
		id: "link-cocos",
		title: "Cocos Creator",
		url: "https://www.cocos.com/",
		category: "游戏引擎",
		lang: "zh",
		desc: "国产 2D/3D 游戏引擎，TypeScript 脚本，小游戏/H5 领域王者",
	},
	{
		id: "link-playcanvas",
		title: "PlayCanvas",
		url: "https://playcanvas.com/",
		category: "游戏引擎",
		lang: "en",
		desc: "开源 WebGL/WebGPU 3D 引擎，浏览器内编辑+发布",
	},
	{
		id: "link-phaser",
		title: "Phaser",
		url: "https://phaser.io/",
		category: "游戏引擎",
		lang: "en",
		desc: "最流行的 HTML5 2D 游戏框架，JavaScript/TypeScript，活跃社区",
	},
	{
		id: "link-love2d",
		title: "LÖVE",
		url: "https://love2d.org/",
		category: "游戏引擎",
		lang: "en",
		desc: "Lua 驱动的 2D 游戏框架，极简 API + 原生性能，快速原型利器",
	},
	{
		id: "link-gamemaker",
		title: "GameMaker",
		url: "https://gamemaker.io/",
		category: "游戏引擎",
		lang: "en",
		desc: "YoYo Games 出品的 2D 游戏引擎，GML 语言+DnD 可视化编程",
	},
	{
		id: "link-construct",
		title: "Construct",
		url: "https://www.construct.net/",
		category: "游戏引擎",
		lang: "en",
		desc: "可视化事件表驱动的 2D 游戏引擎，无需代码，浏览器在线编辑",
	},
	{
		id: "link-stride",
		title: "Stride 3D",
		url: "https://www.stride3d.net/",
		category: "游戏引擎",
		lang: "en",
		desc: "开源 C# 3D 引擎（原 Xenko），.NET 生态+多平台导出+编辑器",
	},
	{
		id: "link-ambient",
		title: "Ambient",
		url: "https://ambient.run/",
		category: "素材资源",
		lang: "en",
		desc: "Rust 编写的 Web 优先 3D 引擎，无运行时依赖，浏览器内运行",
	},
	{
		id: "link-machengine",
		title: "Mach Engine",
		url: "https://machengine.org/",
		category: "编程 & 架构",
		lang: "en",
		desc: "Zig 编写的模块化游戏引擎，GPU 优先，零开销抽象",
	},
	{
		id: "link-cocos2dx",
		title: "Cocos2d-x",
		url: "https://www.cocos2d-x.org/",
		category: "游戏引擎",
		lang: "en",
		desc: "老牌 C++ 2D 引擎，跨平台+开源，曾是国内移动游戏开发第一选择",
	},
	{
		id: "link-solar2d",
		title: "Solar2D",
		url: "https://solar2d.com/",
		category: "游戏引擎",
		lang: "en",
		desc: "Lua 驱动的 2D 引擎（原 Corona SDK），快速原型+物理引擎集成",
	},
	{
		id: "link-evergine",
		title: "Evergine",
		url: "https://evergine.com/",
		category: "游戏引擎",
		lang: "en",
		desc: "跨平台 3D 引擎，支持 .NET，原名 Wave Engine，专注工业级渲染",
	},
	{
		id: "link-pygame",
		title: "PyGame",
		url: "https://www.pygame.org/",
		category: "游戏引擎",
		lang: "en",
		desc: "Python 游戏框架，适合快速原型和游戏编程教育",
	},

	/* ===== 开发工具 ===== */
	/* ===== 开发工具 ===== */
	{
		id: "link-gameci",
		title: "Game CI",
		url: "https://game.ci/",
		category: "开发工具",
		lang: "en",
		desc: "游戏 CI/CD 工具集，GitHub Actions 集成 Unity/Godot/Unreal 自动构建",
	},

	/* ===== 素材资源 ===== */
	{
		id: "link-opengameart",
		title: "OpenGameArt",
		url: "https://opengameart.org/",
		category: "素材资源",
		lang: "en",
		desc: "最大的免费游戏美术库，含精灵/纹理/模型/音效，多种 CC 许可证",
	},
	{
		id: "link-freesound",
		title: "Freesound",
		url: "https://freesound.org/",
		category: "素材资源",
		lang: "en",
		desc: "CC 许可音效共享平台，收录数万条真实世界录音和合成音效片段",
	},
	{
		id: "link-game-icons",
		title: "Game-Icons.net",
		url: "https://game-icons.net/",
		category: "素材资源",
		lang: "en",
		desc: "数千款免费可商用游戏 SVG 图标，支持按颜色/大小批量导出",
	},
	{
		id: "link-kenney",
		title: "Kenney Assets",
		url: "https://kenney.nl/",
		category: "素材资源",
		lang: "en",
		desc: "高质量免费游戏素材包（CC0），涵盖 UI/图标/角色/环境/字体等",
	},
	{
		id: "link-textures",
		title: "Textures.com",
		url: "https://www.textures.com/",
		category: "素材资源",
		lang: "en",
		desc: "海量 PBR 材质贴图库，涵盖各类地面/墙面/金属/木纹等游戏材质",
	},
	{
		id: "link-itchio-assets",
		title: "itch.io 素材区",
		url: "https://itch.io/game-assets",
		category: "素材资源",
		lang: "en",
		desc: "独立开发者交易平台，数千款付费/免费游戏素材涵盖 2D/3D/音频/代码",
	},

	/* ===== 音频工具 ===== */
	{
		id: "link-lmms",
		title: "LMMS",
		url: "https://lmms.io/",
		category: "音频工具",
		lang: "en",
		desc: "开源数字音频工作站（DAW），支持 MIDI/VST/LADSPA，可制作游戏配乐",
	},
	{
		id: "link-audacity",
		title: "Audacity",
		url: "https://www.audacityteam.org/",
		category: "音频工具",
		lang: "en",
		desc: "免费开源音频录制 & 多轨编辑，用于游戏音效剪辑/去噪/格式转换",
	},
	{
		id: "link-boscaceoil",
		title: "Bosca Ceoil",
		url: "https://boscaceoil.net/",
		category: "音频工具",
		lang: "en",
		desc: "蓝调音乐作曲工具，初学者友好，可快速生成循环背景音乐旋律",
	},
	{
		id: "link-sfxr",
		title: "sfxr / jsfxr",
		url: "https://sfxr.me/",
		category: "音频工具",
		lang: "en",
		desc: "在线 8bit/16bit 游戏音效生成器，调节参数即时试听并导出 WAV",
	},
	{
		id: "link-musescore",
		title: "MuseScore",
		url: "https://musescore.org/",
		category: "音频工具",
		lang: "en",
		desc: "开源乐谱编辑器，可谱写 MIDI 并导出为音频文件或印刷式乐谱 PDF",
	},

	/* ===== 2D/3D 美术 ===== */
	{
		id: "link-aseprite",
		title: "Aseprite",
		url: "https://www.aseprite.org/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "专业的像素画 & 精灵动图编辑器，支持图层/帧动画/调色板，Steam 有售",
	},
	{
		id: "link-tiled",
		title: "Tiled",
		url: "https://www.mapeditor.org/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "免费灵活的 2D 网格地图编辑器，支持正交/等距/六边形地图，多引擎导出",
	},
	{
		id: "link-spine",
		title: "Spine",
		url: "http://esotericsoftware.com/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "2D 骨骼动画编辑器，被 Unity/UE/Godot/Cocos 等主流引擎广泛集成",
	},
	{
		id: "link-texturepacker",
		title: "TexturePacker",
		url: "https://www.codeandweb.com/texturepacker",
		category: "2D/3D 美术",
		lang: "en",
		desc: "Sprite 帧图打包 & 图集优化工具，支持 Unity/UE/Cocos/Phaser 等引擎导出",
	},
	{
		id: "link-pyxeledit",
		title: "PyxelEdit",
		url: "http://pyxeledit.com/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "专为像素画设计的编辑器，内置瓷砖地图编辑 & 逐帧动画功能",
	},
	{
		id: "link-piskel",
		title: "Piskel",
		url: "https://www.piskelapp.com/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "免费在线像素画编辑器，无需安装即可制作精灵图和逐帧动画",
	},
	{
		id: "link-blender",
		title: "Blender",
		url: "https://www.blender.org/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "开源 3D 建模/雕刻/材质/动画/渲染/合成全流程，游戏资产管线标配",
	},
	{
		id: "link-krita",
		title: "Krita",
		url: "https://krita.org/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "开源数字绘画软件，笔刷引擎强大，适合游戏概念设计与材质贴图绘制",
	},

	/* ===== 开发工具 ===== */
	{
		id: "link-zed",
		title: "Zed Editor",
		url: "https://zed.dev/blog",
		category: "开发工具",
		lang: "en",
		desc: "高性能 Rust 代码编辑器，Atom/树型游标原班人马打造，内置 AI 与协作",
	},
	{
		id: "link-gh-awesome-gamedev-magic",
		title: "magictools (ellisonleao)",
		url: "https://github.com/ellisonleao/magictools",
		category: "开发工具",
		lang: "en",
		desc: "游戏开发资源大全，覆盖图形/代码/音频/设计等，13k+ stars",
	},
	{
		id: "link-gh-awesome-gamedev-skywind",
		title: "awesome-gamedev (skywind3000)",
		url: "https://github.com/skywind3000/awesome-gamedev",
		category: "开发工具",
		lang: "en",
		desc: "中文维护的游戏开发资源列表，引擎/工具/教程齐全",
	},
	{
		id: "link-gh-awesome-gamedev-calinou",
		title: "awesome-gamedev (Calinou)",
		url: "https://github.com/Calinou/awesome-gamedev",
		category: "开发工具",
		lang: "en",
		desc: "仅收录自由/开源软件的游戏开发资源列表",
	},
	{
		id: "link-gh-gamedev-resources",
		title: "GameDev-Resources (Kavex)",
		url: "https://github.com/Kavex/GameDev-Resources",
		category: "开发工具",
		lang: "en",
		desc: "按资产/代码/设计/工具分类的游戏开发资源集",
	},
	{
		id: "link-gh-awesome-game-engine-dev",
		title: "awesome-game-engine-dev (stevinz)",
		url: "https://github.com/stevinz/awesome-game-engine-dev",
		category: "开发工具",
		lang: "en",
		desc: "游戏引擎开发资源专精，架构/渲染/物理等分类",
	},
	{
		id: "link-gh-awesome-gamedev-fronkon",
		title: "Awesome-Gamedev (FronkonGames)",
		url: "https://github.com/FronkonGames/Awesome-Gamedev",
		category: "开发工具",
		lang: "en",
		desc: "代码/工具/教程分类清晰的游戏开发资源合集",
	},
	{
		id: "link-gh-awesome-open-source-games",
		title: "awesome-open-source-games (michelpereira)",
		url: "https://github.com/michelpereira/awesome-open-source-games",
		category: "开发工具",
		lang: "en",
		desc: "开源游戏源码合集，可学习完整项目开发，15k+ stars",
	},
	// Ollama 和 Anthropic Engineering Blog 已移除（不直接相关游戏开发）
	{
		id: "link-renderdoc",
		title: "RenderDoc",
		url: "https://renderdoc.org/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "开源 GPU 调试器，抓帧分析渲染管线，游戏图形调试标配工具",
	},
	{
		id: "link-gimp",
		title: "GIMP",
		url: "https://www.gimp.org/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "开源图像编辑软件，功能接近 Photoshop，适合贴图编辑与概念图",
	},
	{
		id: "link-material-maker",
		title: "Material Maker",
		url: "https://www.materialmaker.org/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "开源节点式 PBR 材质生成工具，类似 Substance Designer，可导出到 Godot/UE",
	},
	/* ===== 开发社区 ===== */

	{
		id: "link-gdc",
		title: "GDC Vault",
		url: "https://www.gdconf.com/",
		category: "视频/频道",
		lang: "en",
		desc: "游戏开发者大会演讲录像与幻灯片，了解游戏工业最新实践的第一现场",
	},

	/* ===== 行业动态 ===== */
	/* ===== 行业动态 ===== */
	{
		id: "x-id-a-carmack",
		title: "John Carmack (@ID_AA_Carmack)",
		url: "https://x.com/ID_AA_Carmack",
		category: "行业动态",
		lang: "en",
		desc: "id Software 联合创始人，Wolfenstein 3D / DOOM / Quake 引擎之父，Oculus CTO，AGI 研究员",
	},
	{
		id: "x-reduz",
		title: "Juan Linietsky (@reduz)",
		url: "https://x.com/reduz",
		category: "行业动态",
		lang: "en",
		desc: "Godot 引擎联合创始人兼核心维护者",
	},
	{
		id: "x-akien",
		title: "Rémi Verschelde (@akien)",
		url: "https://x.com/akien",
		category: "行业动态",
		lang: "en",
		desc: "Godot 引擎核心维护者，发布管理负责人",
	},
	{
		id: "x-ocornut",
		title: "Omar Cornut (@ocornut)",
		url: "https://x.com/ocornut",
		category: "行业动态",
		lang: "en",
		desc: "Dear ImGui 作者，即时模式 GUI 先驱",
	},
	{
		id: "x-raysan5",
		title: "Ray San (@raysan5)",
		url: "https://x.com/raysan5",
		category: "行业动态",
		lang: "en",
		desc: "Raylib 作者，简洁易用的游戏编程库",
	},
	{
		id: "x-aras-p",
		title: "Aras Pranckevičius (@aras_p)",
		url: "https://x.com/aras_p",
		category: "行业动态",
		lang: "en",
		desc: "Unity 前核心开发者，现 Godot 贡献者，图形/性能优化专家",
	},

	/* ===== 行业动态 ===== */
	{
		id: "x-hideo-kojima",
		title: "Hideo Kojima (@HIDEO_KOJIMA_EN)",
		url: "https://x.com/HIDEO_KOJIMA_EN",
		category: "行业动态",
		lang: "en",
		desc: "小岛秀夫，Metal Gear Solid / Death Stranding 制作人，游戏电影化叙事代表人物",
	},
	{
		id: "x-raphkoster",
		title: "Raph Koster (@RaphKoster)",
		url: "https://x.com/RaphKoster",
		category: "行业动态",
		lang: "en",
		desc: "《游戏设计理论》(A Theory of Fun) 作者，Ultima Online / SWG 首席设计师",
	},
	{
		id: "x-j-schell",
		title: "Jesse Schell (@j_schell)",
		url: "https://x.com/j_schell",
		category: "行业动态",
		lang: "en",
		desc: "《游戏设计艺术》(The Art of Game Design) 作者，Schell Games CEO",
	},
	{
		id: "x-levine",
		title: "Ken Levine (@levine)",
		url: "https://x.com/levine",
		category: "行业动态",
		lang: "en",
		desc: "BioShock / System Shock 2 创意总监，叙事驱动游戏设计大师",
	},
	{
		id: "x-ernestadams",
		title: "Ernest Adams (@ErnestAdams)",
		url: "https://x.com/ErnestAdams",
		category: "行业动态",
		lang: "en",
		desc: "《游戏设计基础》作者，资深游戏设计顾问与教育者",
	},
	{
		id: "x-timcain",
		title: "Tim Cain (@TimCain)",
		url: "https://x.com/TimCain",
		category: "行业动态",
		lang: "en",
		desc: "Fallout 系列创始人、主程与首席设计师",
	},

	/* ===== 行业动态 ===== */
	{
		id: "x-cliffyb",
		title: "Cliff Bleszinski (@therealcliffyb)",
		url: "https://x.com/therealcliffyb",
		category: "行业动态",
		lang: "en",
		desc: "Unreal 引擎联合创始人，Gears of War 系列总监，Epic Games 前设计总监",
	},
	{
		id: "x-petermolyneux",
		title: "Peter Molyneux (@PeterMolyneux)",
		url: "https://x.com/PeterMolyneux",
		category: "行业动态",
		lang: "en",
		desc: "Populous / Black & White / Fable 制作人，Bullfrog / Lionhead 创始人",
	},
	{
		id: "x-davidjaffe",
		title: "David Jaffe (@davidscottjaffe)",
		url: "https://x.com/davidscottjaffe",
		category: "行业动态",
		lang: "en",
		desc: "God of War 系列创始人与创意总监，Twisted Metal 制作人",
	},
	{
		id: "x-warrenspector",
		title: "Warren Spector (@WarrenSpector)",
		url: "https://x.com/WarrenSpector",
		category: "行业动态",
		lang: "en",
		desc: "Deus Ex 导演，Looking Glass / Ion Storm 元老，沉浸式模拟(Immersive Sim)代表人物",
	},

	/* ===== 行业动态 ===== */
	{
		id: "x-notch",
		title: "Markus Persson (@notch)",
		url: "https://x.com/notch",
		category: "行业动态",
		lang: "en",
		desc: "Minecraft 创始人，Mojang 创始人与独立游戏传奇",
	},
	{
		id: "x-tobyfox",
		title: "Toby Fox (@tobyfox)",
		url: "https://x.com/tobyfox",
		category: "行业动态",
		lang: "en",
		desc: "Undertale / Deltarune 作者，独立 RPG 叙事标杆",
	},
	{
		id: "x-concernedape",
		title: "Eric Barone (@ConcernedApe)",
		url: "https://x.com/ConcernedApe",
		category: "行业动态",
		lang: "en",
		desc: "Stardew Valley 单人开发者，独立游戏持久运营典范",
	},
	{
		id: "x-lucaspope",
		title: "Lucas Pope (@dukope)",
		url: "https://x.com/dukope",
		category: "行业动态",
		lang: "en",
		desc: "Papers, Please / Return of the Obra Dinn 作者，创新玩法设计代表",
	},
	{
		id: "x-tommyrefenes",
		title: "Tommy Refenes (@tommyrefenes)",
		url: "https://x.com/tommyrefenes",
		category: "行业动态",
		lang: "en",
		desc: "Super Meat Boy 联合开发者，独立游戏平台跳跃经典",
	},
	{
		id: "x-jonathanblow",
		title: "Jonathan Blow (@JonathanBlow)",
		url: "https://x.com/JonathanBlow",
		category: "行业动态",
		lang: "en",
		desc: "Braid / The Witness 作者，Jai 语言创作者，游戏设计哲学家",
	},

	/* ===== 行业动态 ===== */
	{
		id: "x-freyaholmer",
		title: "Freya Holmér (@FreyaHolmer)",
		url: "https://x.com/FreyaHolmer",
		category: "行业动态",
		lang: "en",
		desc: "Shader / 数学 / 渲染教育者，Unity 技术美术专家",
	},
	{
		id: "x-iquilez",
		title: "Inigo Quilez (@iquilezles)",
		url: "https://x.com/iquilezles",
		category: "行业动态",
		lang: "en",
		desc: "Shader 艺术大师，Shadertoy / Inigo Quilez 博客作者，渲染技术布道者",
	},
	{
		id: "x-sebastianlague",
		title: "Sebastian Lague (@SebastianLague)",
		url: "https://x.com/SebastianLague",
		category: "行业动态",
		lang: "en",
		desc: "游戏开发 YouTuber，编程与算法可视化教程作者",
	},

	/* ===== 行业动态 ===== */
	{
		id: "x-godotengine",
		title: "Godot Engine (@godotengine)",
		url: "https://x.com/godotengine",
		category: "行业动态",
		lang: "en",
		desc: "Godot 引擎官方账号，发布更新公告与社区动态",
	},
	{
		id: "x-unity",
		title: "Unity (@unity)",
		url: "https://x.com/unity",
		category: "行业动态",
		lang: "en",
		desc: "Unity 引擎官方账号",
	},
	{
		id: "x-unrealengine",
		title: "Unreal Engine (@UnrealEngine)",
		url: "https://x.com/UnrealEngine",
		category: "行业动态",
		lang: "en",
		desc: "Unreal 引擎官方账号，版本发布与技术展示",
	},
	{
		id: "x-itchio",
		title: "itch.io (@itchio)",
		url: "https://x.com/itchio",
		category: "行业动态",
		lang: "en",
		desc: "独立游戏平台 itch.io 官方账号，精选独立游戏推荐",
	},
	{
		id: "x-gdc",
		title: "GDC (@Official_GDC)",
		url: "https://x.com/Official_GDC",
		category: "行业动态",
		lang: "en",
		desc: "Game Developers Conference 官方账号，行业演讲与活动信息",
	},
	{
		id: "x-nintendo",
		title: "Nintendo (@Nintendo)",
		url: "https://x.com/Nintendo",
		category: "行业动态",
		lang: "en",
		desc: "任天堂官方账号，游戏发售与直面会信息",
	},
	{
		id: "x-playstation",
		title: "PlayStation (@PlayStation)",
		url: "https://x.com/PlayStation",
		category: "行业动态",
		lang: "en",
		desc: "PlayStation 官方账号，新作发布与 PlayStation 生态信息",
	},

	/* ===== 行业动态 ===== */
	{
		id: "x-gamedevdotcom",
		title: "Game Developer (@gamedevdotcom)",
		url: "https://x.com/gamedevdotcom",
		category: "行业动态",
		lang: "en",
		desc: "Game Developer 杂志（原 Gamasutra）官方账号，游戏开发深度内容",
	},
	{
		id: "x-igda",
		title: "IGDA (@IGDA)",
		url: "https://x.com/IGDA",
		category: "行业动态",
		lang: "en",
		desc: "国际游戏开发者协会，行业标准与开发者权益倡导",
	},

	/* ===== 开发社区 ===== */
	{
		id: "zhihu-studygame",
		title: "自学游戏开发",
		url: "https://zhuanlan.zhihu.com/studygame",
		category: "开发社区",
		lang: "zh",
		desc: "从零开始的游戏开发入门与进阶，覆盖程序/策划/美术全方向",
	},
	{
		id: "zhihu-highquality",
		title: "高品质游戏开发",
		url: "https://zhuanlan.zhihu.com/c_119702958",
		category: "游戏设计",
		lang: "zh",
		desc: "收集高品质游戏开发原创文章，涵盖技术/美术/策划/管理",
	},
	{
		id: "zhihu-gametech",
		title: "游戏开发技术",
		url: "https://zhuanlan.zhihu.com/gametech",
		category: "编程 & 架构",
		lang: "zh",
		desc: "游戏开发技术文章，客户端/图形/引擎/TA 方向干货",
	},
	{
		id: "zhihu-gamemaker",
		title: "游戏制作笔记",
		url: "https://zhuanlan.zhihu.com/gamemaker",
		category: "游戏设计",
		lang: "zh",
		desc: "独立游戏制作经验分享，从立项到发布的完整流程记录",
	},
	{
		id: "zhihu-chuyunfan",
		title: "楚云帆的游戏行业观察",
		url: "https://zhuanlan.zhihu.com/chuyunfan",
		category: "行业动态",
		lang: "zh",
		desc: "资深游戏媒体人，游戏行业历史与产业分析",
	},

	/* ===== 视频/频道 ===== */
	{
		id: "yt-gmtk",
		title: "Game Maker's Toolkit",
		url: "https://www.youtube.com/@GMTK",
		category: "视频/频道",
		lang: "en",
		desc: "Mark Brown 主持，游戏设计深度拆解，从关卡设计到机制分析的标杆频道",
	},
	{
		id: "yt-designdoc",
		title: "Design Doc",
		url: "https://www.youtube.com/@DesignDoc",
		category: "视频/频道",
		lang: "en",
		desc: "游戏设计文档风格分析，以学术化视角探讨游戏机制与玩家心理",
	},
	{
		id: "yt-extracredits",
		title: "Extra Credits",
		url: "https://www.youtube.com/@ExtraCredits",
		category: "视频/频道",
		lang: "en",
		desc: "游戏设计理论动画化讲解，历史/心理学/叙事多角度覆盖",
	},
	{
		id: "yt-newframeplus",
		title: "New Frame Plus",
		url: "https://www.youtube.com/@NewFramePlus",
		category: "视频/频道",
		lang: "en",
		desc: "游戏动画设计深度分析，拆解动作帧与手感设计的秘密",
	},
	{
		id: "yt-writingongames",
		title: "Writing on Games",
		url: "https://www.youtube.com/@WritingOnGames",
		category: "视频/频道",
		lang: "en",
		desc: "游戏叙事/编剧/世界观构建的深度分析频道",
	},
	{
		id: "yt-architect",
		title: "Adam Millard (The Architect of Games)",
		url: "https://www.youtube.com/@ArchitectOfGames",
		category: "视频/频道",
		lang: "en",
		desc: "以建筑学隐喻拆解游戏设计，系统设计与玩家体验分析",
	},
	{
		id: "yt-brackeys",
		title: "Brackeys",
		url: "https://www.youtube.com/@Brackeys",
		category: "视频/频道",
		lang: "en",
		desc: "Unity 游戏开发教程标杆，零基础入门到完整项目制作",
	},
	{
		id: "yt-sebastianlague",
		title: "Sebastian Lague",
		url: "https://www.youtube.com/@SebastianLague",
		category: "视频/频道",
		lang: "en",
		desc: "编程与算法可视化，游戏开发/物理模拟/图形学等跨领域教程",
	},
	{
		id: "yt-cherno",
		title: "The Cherno",
		url: "https://www.youtube.com/@TheCherno",
		category: "视频/频道",
		lang: "en",
		desc: "C++ / 游戏引擎开发系列教程，从零构建游戏引擎的经典频道",
	},
	{
		id: "yt-codemonkey",
		title: "Code Monkey",
		url: "https://www.youtube.com/@CodeMonkeyUnity",
		category: "视频/频道",
		lang: "en",
		desc: "Unity 完整项目教程，从原型到发布的实战流程",
	},
	{
		id: "yt-gdquest",
		title: "GDQuest",
		url: "https://www.youtube.com/@GDQuest",
		category: "视频/频道",
		lang: "en",
		desc: "Godot 引擎系统化教程，从入门到高级编程",
	},
	{
		id: "yt-heartbeast",
		title: "HeartBeast",
		url: "https://www.youtube.com/@HeartBeast",
		category: "视频/频道",
		lang: "en",
		desc: "Godot / GameMaker Studio 2D 游戏开发教程",
	},
	{
		id: "yt-thinmatrix",
		title: "ThinMatrix",
		url: "https://www.youtube.com/@ThinMatrix",
		category: "视频/频道",
		lang: "en",
		desc: "OpenGL / Java 游戏开发日志，从零构建 3D 游戏引擎",
	},
	{
		id: "yt-miziziziz",
		title: "Miziziziz",
		url: "https://www.youtube.com/@Miziziziz",
		category: "视频/频道",
		lang: "en",
		desc: "游戏开发日志/极限开发挑战，快速原型制作流程记录",
	},
	{
		id: "yt-gdc",
		title: "GDC (Game Developers Conference)",
		url: "https://www.youtube.com/@GDC",
		category: "视频/频道",
		lang: "en",
		desc: "GDC 官方频道，历年开发者大会演讲录像",
	},
	{
		id: "yt-unreal",
		title: "Unreal Engine",
		url: "https://www.youtube.com/@UnrealEngine",
		category: "视频/频道",
		lang: "en",
		desc: "Unreal 引擎官方频道，版本新特性与技术教程",
	},
	{
		id: "yt-unity",
		title: "Unity",
		url: "https://www.youtube.com/@Unity",
		category: "视频/频道",
		lang: "en",
		desc: "Unity 引擎官方频道，教程/案例/技术分享",
	},
	{
		id: "yt-godot",
		title: "Godot Engine",
		url: "https://www.youtube.com/@GodotEngine",
		category: "视频/频道",
		lang: "en",
		desc: "Godot 引擎官方频道，版本发布/教程/社区展示",
	},

	/* ===== 开发社区 ===== */

	{
		id: "reddit-gameengines",
		title: "r/gameengines",
		url: "https://www.reddit.com/r/gameengines/",
		category: "开发社区",
		lang: "en",
		desc: "自研引擎/引擎选型/渲染技术讨论子版",
	},

	{
		id: "reddit-leveldesign",
		title: "r/leveldesign",
		url: "https://www.reddit.com/r/leveldesign/",
		category: "开发社区",
		lang: "en",
		desc: "关卡设计交流/展示/反馈子版",
	},

	{
		id: "reddit-basebuilding",
		title: "r/BaseBuildingGames",
		url: "https://www.reddit.com/r/BaseBuildingGames/",
		category: "开发社区",
		lang: "en",
		desc: "基地建设/殖民模拟类游戏设计与开发讨论",
	},

	{
		id: "reddit-4x",
		title: "r/4Xgaming",
		url: "https://www.reddit.com/r/4Xgaming/",
		category: "开发社区",
		lang: "en",
		desc: "4X/策略类游戏设计与开发讨论",
	},

	{
		id: "reddit-aigamedev",
		title: "r/aigamedev",
		url: "https://www.reddit.com/r/aigamedev/",
		category: "开发社区",
		lang: "en",
		desc: "AI 游戏开发/程序化生成技术讨论",
	},

	{
		id: "reddit-gameideas",
		title: "r/gameideas",
		url: "https://www.reddit.com/r/gameideas/",
		category: "开发社区",
		lang: "en",
		desc: "游戏创意/概念分享与讨论子版",
	},
	{
		id: "reddit-gamedev",
		title: "r/gamedev",
		url: "https://www.reddit.com/r/gamedev/",
		category: "开发社区",
		lang: "en",
		desc: "游戏开发综合讨论，技术/设计/发行/职业全覆盖，最大游戏开发社区",
	},
	{
		id: "reddit-gamedesign",
		title: "r/gamedesign",
		url: "https://www.reddit.com/r/gamedesign/",
		category: "开发社区",
		lang: "en",
		desc: "游戏设计理论讨论，机制/叙事/交互设计的专业讨论区",
	},
	{
		id: "reddit-unity3d",
		title: "r/Unity3D",
		url: "https://www.reddit.com/r/Unity3D/",
		category: "开发社区",
		lang: "en",
		desc: "Unity 引擎开发社区，教程/展示/技术求助",
	},
	{
		id: "reddit-unreal",
		title: "r/unrealengine",
		url: "https://www.reddit.com/r/unrealengine/",
		category: "开发社区",
		lang: "en",
		desc: "Unreal 引擎开发社区，蓝图/C++/渲染/技术讨论",
	},
	{
		id: "reddit-godot",
		title: "r/godot",
		url: "https://www.reddit.com/r/godot/",
		category: "开发社区",
		lang: "en",
		desc: "Godot 引擎开发社区，教程/插件/游戏展示",
	},
	{
		id: "reddit-indiedev",
		title: "r/IndieDev",
		url: "https://www.reddit.com/r/IndieDev/",
		category: "开发社区",
		lang: "en",
		desc: "独立游戏开发者社区，开发日志/反馈/经验交流",
	},
	{
		id: "reddit-indiegaming",
		title: "r/IndieGaming",
		url: "https://www.reddit.com/r/IndieGaming/",
		category: "开发社区",
		lang: "en",
		desc: "独立游戏推广与发现，玩家与开发者交流平台",
	},
	{
		id: "reddit-gameindustry",
		title: "r/gameindustry",
		url: "https://www.reddit.com/r/gameindustry/",
		category: "开发社区",
		lang: "en",
		desc: "游戏行业新闻与讨论，商业/发行/职场话题",
	},
	{
		id: "reddit-pcgaming",
		title: "r/pcgaming",
		url: "https://www.reddit.com/r/pcgaming/",
		category: "开发社区",
		lang: "en",
		desc: "PC 游戏综合讨论，硬件/游戏推荐/行业新闻",
	},
	{
		id: "reddit-gameassets",
		title: "r/gameassets",
		url: "https://www.reddit.com/r/gameassets/",
		category: "开发社区",
		lang: "en",
		desc: "免费/开源游戏素材分享，模型/音效/UI 资源",
	},

	/* ===== 开发工具 ===== */
	{
		id: "link-opencode",
		title: "OpenCode.ai",
		url: "https://opencode.ai/",
		category: "开发工具",
		lang: "en",
		desc: "AI 辅助编程平台",
	},
	{
		id: "link-pi-dev",
		title: "Pi Coding Agent",
		url: "https://pi.dev/",
		category: "开发工具",
		lang: "en",
		desc: "AI 编程助手，支持多模型协作",
	},
	{
		id: "link-kiss-translator",
		title: "Kiss Translator",
		url: "https://chromewebstore.google.com/detail/kiss-translator/bdiifdefkgmcblbcghdlonllpjhhjgof",
		category: "开发工具",
		lang: "en",
		desc: "Chrome 扩展，网页/代码翻译",
	},
	{
		id: "link-sourcegit",
		title: "SourceGit",
		url: "https://sourcegit-scm.github.io/",
		category: "开发工具",
		lang: "en",
		desc: "开源 Git GUI 客户端，跨平台",
	},

	/* ===== 游戏设计 ===== */
	{
		id: "link-designer-notes",
		title: "Designer Notes",
		url: "http://www.designer-notes.com/",
		category: "游戏设计",
		lang: "en",
		desc: "Soren Johnson（文明IV主设计师）的游戏设计播客/博客",
	},
	{
		id: "link-keith-burgun",
		title: "Keith Burgun",
		url: "http://keithburgun.net/",
		category: "游戏设计",
		lang: "en",
		desc: "游戏设计理论家，著有《Game Design Theory》",
	},
	{
		id: "link-gamedesign-aspect",
		title: "Game Design Aspect",
		url: "http://gamedesignaspect.blogspot.com/",
		category: "游戏设计",
		lang: "en",
		desc: "Sande Chen 的游戏编剧/设计博客",
	},

	/* ===== 网站 ===== */
	{
		id: "link-rami-ismail",
		title: "Rami Ismail (LTPF)",
		url: "https://ltpf.ramiismail.com/",
		category: "开发社区",
		lang: "en",
		desc: "Vlambeer 联合创始人，独立游戏行业顾问与设计专栏",
	},
	{
		id: "link-a16z-games",
		title: "A16Z Games (Speedrun)",
		url: "https://speedrun.substack.com/",
		category: "发行/运营",
		lang: "en",
		desc: "顶级 VC 的游戏行业分析 Newsletter",
	},
	{
		id: "link-elite-game-devs",
		title: "Elite Game Developers",
		url: "https://elitegamedevelopers.substack.com/",
		category: "开发社区",
		lang: "en",
		desc: "游戏开发者深度访谈与商业分析 Newsletter",
	},
	{
		id: "link-cowlevel",
		title: "奶牛关",
		url: "https://cowlevel.net/",
		category: "开发社区",
		lang: "zh",
		desc: "中文游戏设计/开发社区",
	},

	/* ===== 编程 & 架构 ===== */
	{
		id: "link-riot-eng",
		title: "Riot Games Engineering",
		url: "https://engineering.riotgames.com/",
		category: "编程 & 架构",
		lang: "en",
		desc: "Riot 技术博客，LOL/Valorant 的技术实践",
	},
	{
		id: "link-fabien-sanglard",
		title: "Fabien Sanglard",
		url: "https://fabiensanglard.net/",
		category: "编程 & 架构",
		lang: "en",
		desc: "游戏引擎源码深度逆向分析（Quake/DOOM 等）",
	},
	{
		id: "link-tom-looman",
		title: "Tom Looman",
		url: "https://www.tomlooman.com/",
		category: "编程 & 架构",
		lang: "en",
		desc: "Unreal Engine 系统教程与性能优化",
	},
	{
		id: "link-internal-pointers",
		title: "Internal Pointers",
		url: "https://www.internalpointers.com/",
		category: "编程 & 架构",
		lang: "en",
		desc: "C++ 与编程底层技术深度文章",
	},
	{
		id: "link-gabriel-gambetta",
		title: "Gabriel Gambetta",
		url: "https://www.gabrielgambetta.com/",
		category: "编程 & 架构",
		lang: "en",
		desc: "多人游戏联网与计算机图形学经典教程",
	},
	{
		id: "link-adrian-courreges",
		title: "Adrian Courreges",
		url: "https://www.adriancourreges.com/",
		category: "编程 & 架构",
		lang: "en",
		desc: "3A 游戏图形技术拆解（MGS V/DOOM/战神等）",
	},
	{
		id: "link-box2d",
		title: "Box2D (Erin Catto)",
		url: "https://box2d.org/",
		category: "编程 & 架构",
		lang: "en",
		desc: "物理引擎开发者博客，GDC 演讲",
	},
	{
		id: "link-evan-todd",
		title: "Evan Todd",
		url: "https://etodd.io/",
		category: "编程 & 架构",
		lang: "en",
		desc: "「Poor Man's」系列，独立游戏工具开发",
	},
	{
		id: "link-ben-ui",
		title: "Ben UI",
		url: "https://benui.ca/",
		category: "编程 & 架构",
		lang: "en",
		desc: "Unreal Engine C++ UI 教程",
	},

	/* ===== 游戏设计 ===== */
	{
		id: "link-liz-england",
		title: "Liz England",
		url: "https://lizengland.com/",
		category: "游戏设计",
		lang: "en",
		desc: "AAA 游戏设计师（Respawn/微软/Insomniac）",
	},
	{
		id: "link-sirlin",
		title: "Sirlin.net",
		url: "https://www.sirlin.net/",
		category: "游戏设计",
		lang: "en",
		desc: "格斗游戏设计理论（Street Fighter HD Remix 设计师）",
	},

	/* ===== 游戏引擎 ===== */
	{
		id: "link-chickensoft",
		title: "Chickensoft",
		url: "https://chickensoft.games/",
		category: "游戏引擎",
		lang: "en",
		desc: "Godot/C# 游戏架构博客",
	},

	/* ===== 2D/3D 美术 ===== */
	{
		id: "link-lospec",
		title: "Lospec",
		url: "https://lospec.com/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "像素艺术社区，含调色板生成器/像素画教程数据库/编辑器工具集",
	},
	{
		id: "link-pixeljoint",
		title: "PixelJoint",
		url: "https://pixeljoint.com/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "最老牌像素艺术社区，作品展示/挑战赛/教程",
	},
	{
		id: "link-slynyrd",
		title: "Slynyrd",
		url: "https://www.slynyrd.com/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "像素画大师级教程（Pixelblog），覆盖配色/场景/角色/动画",
	},
	{
		id: "link-retronator",
		title: "Retronator",
		url: "https://www.retronator.com/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "像素艺术每日新闻与游戏开发博客，含 Pixel Art Academy 开发日志",
	},
	{
		id: "link-mega-voxels",
		title: "Mega Voxels",
		url: "https://www.megavoxels.com/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "像素/Voxel 3D 建模教程与工具",
	},
	{
		id: "link-spritecraft",
		title: "Spritecraft Learn",
		url: "https://spritecraft-learn.com/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "免费游戏美术与像素画结构化学堂，含结构化课程",
	},

	/* ===== 视频/频道 ===== */
	{
		id: "yt-adamcyounis",
		title: "AdamCYounis",
		url: "https://www.youtube.com/@AdamCYounis",
		category: "视频/频道",
		lang: "en",
		desc: "Aseprite 像素艺术教程标杆频道，从入门到高级动画",
	},
	{
		id: "yt-brandon-james-greer",
		title: "Brandon James Greer",
		url: "https://www.youtube.com/@BrandonJGreer",
		category: "视频/频道",
		lang: "en",
		desc: "像素艺术/游戏美术教程，涵盖角色/场景/动画",
	},
	{
		id: "yt-ansimuz",
		title: "Ansimuz",
		url: "https://www.youtube.com/@ansimuz",
		category: "视频/频道",
		lang: "en",
		desc: "像素艺术 + 独立游戏开发，免费素材与教程",
	},
	{
		id: "yt-pixel-art-journey",
		title: "Pixel Art Journey (Pedro Medeiros)",
		url: "https://www.youtube.com/@PixelArtJourney",
		category: "视频/频道",
		lang: "en",
		desc: "像素画系统教程，Godot 引擎创始人之一主讲",
	},
	{
		id: "yt-slynyrd",
		title: "Slynyrd",
		url: "https://www.youtube.com/@slynyrd",
		category: "视频/频道",
		lang: "en",
		desc: "像素画教程，同名博客联动，作品展示与技法讲解",
	},

	/* ===== 发行/运营 ===== */
	{
		id: "link-steamworks",
		title: "Steamworks",
		url: "https://partner.steamgames.com/",
		category: "发行/运营",
		lang: "en",
		desc: "Steam 官方开发者后台，游戏上架配置、商店页管理与销售数据分析",
	},
	{
		id: "link-howtomarketagame",
		title: "How To Market A Game",
		url: "https://howtomarketagame.com/",
		category: "发行/运营",
		lang: "en",
		desc: "独立游戏营销策略资源站（Chris Zukowski），含博客/播客/课程",
	},
	{
		id: "link-epic-publishing",
		title: "Epic Games Store Publishing",
		url: "https://store.epicgames.com/en-US/publish",
		category: "发行/运营",
		lang: "en",
		desc: "Epic 游戏商城开发者发行后台，游戏提交与商店管理",
	},
	{
		id: "link-indie-game-academy",
		title: "Indie Game Academy",
		url: "https://indiegameacademy.com/",
		category: "发行/运营",
		lang: "en",
		desc: "独立游戏全流程制作与营销在线课程平台",
	},
	{
		id: "link-itch-publishing",
		title: "itch.io 发布指南",
		url: "https://itch.io/docs/creators/",
		category: "发行/运营",
		lang: "en",
		desc: "itch.io 开发者文档：定价/折扣/Sales/社区运营等发布指南",
	},

	/* ===== 游戏本地化 ===== */
	{
		id: "link-igda-locsig",
		title: "IGDA Localization SIG",
		url: "https://igda.org/sigs/localization/",
		category: "游戏本地化",
		lang: "en",
		desc: "国际游戏开发者协会本地化特别兴趣组，最佳实践/社区/资源",
	},
	{
		id: "link-locpick",
		title: "Locpick",
		url: "https://locpick.com/blog/",
		category: "游戏本地化",
		lang: "en",
		desc: "专业游戏本地化博客，涵盖各语言本地化技术指南",
	},
	{
		id: "link-better-i18n",
		title: "Better I18N",
		url: "https://better-i18n.com/en/blog/",
		category: "游戏本地化",
		lang: "en",
		desc: "游戏国际化与本地化完整指南，从翻译到文化适配的全流程",
	},
	{
		id: "link-transloot",
		title: "Transloot",
		url: "https://www.transloot.com/blog/",
		category: "游戏本地化",
		lang: "en",
		desc: "独立游戏本地化工具，AI 翻译 + LQA 评分，PO/JSON/CSV 格式支持",
	},
	{
		id: "link-crowdin",
		title: "Crowdin",
		url: "https://crowdin.com/",
		category: "游戏本地化",
		lang: "en",
		desc: "主流游戏本地化管理平台，集成 GitHub/Jira/Unity/UE，团队协作",
	},
	{
		id: "link-weblate",
		title: "Weblate",
		url: "https://weblate.org/",
		category: "游戏本地化",
		lang: "en",
		desc: "开源本地化平台，支持自托管，适合开源项目和社区翻译",
	},
	{
		id: "link-lokalise",
		title: "Lokalise",
		url: "https://lokalise.com/",
		category: "游戏本地化",
		lang: "en",
		desc: "开发者导向的本地化平台，CLI/API 集成，移动端 OTA 翻译更新",
	},
	{
		id: "link-poeditor",
		title: "POEditor",
		url: "https://poeditor.com/",
		category: "游戏本地化",
		lang: "en",
		desc: "轻量级本地化管理平台，支持 PO/XLIFF/JSON 等格式，按单词计费",
	},
	{
		id: "link-reddit-gamelocalization",
		title: "r/gamelocalization",
		url: "https://www.reddit.com/r/gamelocalization/",
		category: "游戏本地化",
		lang: "en",
		desc: "Reddit 游戏本地化社区，翻译/工具/从业者交流",
	},
	{
		id: "link-game-icons",
		title: "Game-Icons.net",
		url: "https://game-icons.net/",
		category: "UI/UX 设计",
		lang: "en",
		desc: "4000+ 免费游戏图标 SVG 库，CC BY 3.0 许可，可自定义颜色大小",
	},

	/* ===== 音频工具 ===== */
	{
		id: "link-fmod",
		title: "FMOD",
		url: "https://www.fmod.com/",
		category: "音频工具",
		lang: "en",
		desc: "跨平台游戏音频中间件，独立开发免费许可，Unity/Unreal/Godot 原生集成",
	},
	{
		id: "link-chiptone",
		title: "Chiptone / BFXR",
		url: "https://bfxr.net/",
		category: "音频工具",
		lang: "en",
		desc: "在线游戏音效生成器，BFXR 改进了 sfxr，支持更丰富音色和预设",
	},

	/* ===== 游戏测试 ===== */
	{
		id: "link-awesome-game-tester",
		title: "Awesome Game Tester (jianbing)",
		url: "https://github.com/jianbing/awesome-game-tester",
		category: "游戏测试",
		lang: "zh",
		desc: "GitHub 游戏测试资源大全，学习资料/工具/框架/性能监控，中文维护",
	},
	{
		id: "link-game-test-tutorial",
		title: "游戏测试完全指南",
		url: "https://zsc.github.io/game_test_tutorial/",
		category: "游戏测试",
		lang: "zh",
		desc: "从人工测试到智能自动化的系统化教程，覆盖街机到 3A 游戏",
	},
	{
		id: "link-debug-room",
		title: "Debug Room",
		url: "https://gametesting.site/",
		category: "游戏测试",
		lang: "ja",
		desc: "日文游戏 QA 博客，20 年以上经验积累，分享测试实战知见",
	},
	{
		id: "link-playable-qa",
		title: "Playable!",
		url: "https://playable.qa/",
		category: "游戏测试",
		lang: "ja",
		desc: "日本 AI 游戏 QA 自动化平台，利用生成 AI 实现超高速自动化测试",
	},
	{
		id: "link-wetest",
		title: "WeTest 腾讯",
		url: "https://wetest.net/",
		category: "游戏测试",
		lang: "zh",
		desc: "腾讯游戏测试平台，AI 自动化测试/性能监控/兼容性测试",
	},
	{
		id: "link-gametester-gg",
		title: "Game Tester",
		url: "https://gametester.gg/",
		category: "游戏测试",
		lang: "en",
		desc: "连接游戏开发者与测试人员的平台，PC/Android/iOS 游戏众测",
	},
	{
		id: "link-testerhome",
		title: "TesterHome 测试之家",
		url: "https://testerhome.com/",
		category: "游戏测试",
		lang: "zh",
		desc: "国内测试技术社区，公益/开源/分享，有游戏测试板块和资源",
	},
	{
		id: "link-awesome-testing",
		title: "Awesome Testing (TheJambo)",
		url: "https://github.com/TheJambo/awesome-testing",
		category: "游戏测试",
		lang: "en",
		desc: "通用测试资源列表（含游戏测试），学习/工具/自动化框架索引",
	},
	{
		id: "link-gameqa-testmat",
		title: "TestMat.io 游戏测试指南",
		url: "https://testomat.io/blog/game-testing-management/",
		category: "游戏测试",
		lang: "en",
		desc: "游戏软件测试管理实战指南，功能/性能/兼容性全覆盖",
	},
	{
		id: "link-craftpix",
		title: "CraftPix",
		url: "https://craftpix.net/",
		category: "素材资源",
		lang: "en",
		desc: "2D 游戏素材商店，含免费与付费精灵/图块/UI/角色/背景素材",
	},
	{
		id: "link-gamedev-market",
		title: "GameDev Market",
		url: "https://www.gamedevmarket.net/",
		category: "素材资源",
		lang: "en",
		desc: "游戏开发素材自由市场，艺术家与开发者直接交易",
	},

	/* ===== 游戏引擎 ===== */
	{
		id: "link-pico8",
		title: "PICO-8",
		url: "https://www.lexaloffle.com/pico-8.php",
		category: "游戏引擎",
		lang: "en",
		desc: "复古梦幻主机（Fantasy Console），像素游戏创作与分享社区",
	},
	{
		id: "link-gbstudio",
		title: "GB Studio",
		url: "https://www.gbstudio.dev/",
		category: "游戏引擎",
		lang: "en",
		desc: "Game Boy 风格拖拽式游戏制作工具，无需编程知识即可制作经典掌机风格游戏",
	},
	{
		id: "link-rpgmaker",
		title: "RPG Maker",
		url: "https://www.rpgmakerweb.com/",
		category: "游戏引擎",
		lang: "en",
		desc: "经典 RPG 游戏制作工具系列，可视化编辑 + 事件系统",
	},
	{
		id: "link-puzzlescript",
		title: "PuzzleScript",
		url: "https://www.puzzlescript.net/",
		category: "游戏引擎",
		lang: "en",
		desc: "开源益智游戏引擎与在线编辑器，基于浏览器编写和分享解谜游戏",
	},
	{
		id: "link-bitsy",
		title: "Bitsy",
		url: "https://bitsy.org/",
		category: "游戏引擎",
		lang: "en",
		desc: "轻量级微型游戏编辑器，适合制作叙事驱动的短篇像素游戏",
	},

	/* ===== 开发工具 ===== */
	{
		id: "link-hacknplan",
		title: "HacknPlan",
		url: "https://hacknplan.com/",
		category: "开发工具",
		lang: "en",
		desc: "面向游戏开发团队的项目管理工具，支持看板/路线图/文档/版本计划",
	},
	{
		id: "link-codecks",
		title: "Codecks",
		url: "https://www.codecks.io/",
		category: "开发工具",
		lang: "en",
		desc: "类卡牌游戏交互的游戏开发项目管理工具，支持看板/标签/里程碑",
	},

	/* ===== 2D/3D 美术 ===== */
	{
		id: "link-dragonbones",
		title: "DragonBones",
		url: "https://dragonbones.com/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "开源 2D 骨骼动画工具，支持 Spine 数据格式兼容，免费商用",
	},
	{
		id: "link-aseprite-ext",
		title: "Aseprite 社区扩展 (aseprite-níce)",
		url: "https://github.com/nicebytegames/aseprite-nice-extensions",
		category: "2D/3D 美术",
		lang: "en",
		desc: "Aseprite 实用社区扩展合集，增强像素动画工作流",
	},
	{
		id: "link-pixel-logic",
		title: "Pixel Logic - A Pixel Art Guide",
		url: "https://pixellogicbook.com/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "像素画系统教程电子书，覆盖线条/颜色/光影/动画全流程",
	},
	{
		id: "link-blockbench",
		title: "Blockbench",
		url: "https://www.blockbench.net/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "低多边形 3D 建模工具，专为 Minecraft 风格和像素风游戏设计",
	},
	{
		id: "link-piskel",
		title: "Piskel (在线版)",
		url: "https://www.piskelapp.com/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "在线像素画编辑器，免费开源，支持精灵动画帧编辑与导出",
	},
	{
		id: "link-spine",
		title: "Spine",
		url: "https://esotericsoftware.com/",
		category: "2D/3D 美术",
		lang: "en",
		desc: "2D 骨骼动画工具，游戏行业标准，支持网格变形/蒙皮/动画混合",
	},
]
/**
 * 所有工具/资源链接（静态数据源）
 * 在前端"网址"标签页中按分类展示
 */
export const linkSource: NewsSource = {
	name: "开发工具链接",
	lang: "all",
	fetch: async () => {
		return links.map((item) => ({
			id: item.id,
			title: item.title,
			url: item.url,
			sourceName: item.category,
			extra: {
				hover: item.desc,
				info: item.category,
			},
		}));
	},
};

/** 按分类分组 */
export function getLinksByCategory(): Record<string, LinkEntry[]> {
	const groups: Record<string, LinkEntry[]> = {};
	for (const link of links) {
		if (!groups[link.category]) groups[link.category] = [];
		groups[link.category].push(link);
	}
	return groups;
}
