import type { NewsSource } from "../utils/types";

/**
 * 游戏开发工具/资源链接源（静态数据，无 RSS 抓取）
 * 按分类展示，帮助用户发现有用的开发站点
 */

interface LinkEntry {
	id: string;
	title: string;
	url: string;
	category: string;
	lang: string;
	desc?: string;
}

const links: LinkEntry[] = [
	/* ===== 社区（动态最强） ===== */
	{
		id: "link-gamedevnet",
		title: "GameDev.net",
		url: "https://gamedev.net/",
		category: "社区",
		lang: "en",
		desc: "老牌游戏开发者社区，活跃论坛/技术文章/博客/资源分享",
	},
	{
		id: "link-tigsource",
		title: "TIGSource",
		url: "https://www.tigsource.com/",
		category: "社区",
		lang: "en",
		desc: "经典独立游戏论坛，开发者发布 Devlog 与开发讨论的首选地之一",
	},
	{
		id: "link-gh-learn-gamedev",
		title: "awesome-learn-gamedev (dawdle-deer)",
		url: "https://github.com/dawdle-deer/awesome-learn-gamedev",
		category: "社区",
		lang: "en",
		desc: "游戏开发学习资源导航，从零开始的系统学习路径",
	},
	{
		id: "link-reddit-gamedev",
		title: "Reddit r/gamedev",
		url: "https://www.reddit.com/r/gamedev/",
		category: "社区",
		lang: "en",
		desc: "Reddit 最大游戏开发子版，每日问答/经验分享/作品展示（网络受限）",
	},
	{
		id: "link-reddit-gamedesign",
		title: "Reddit r/GameDesign",
		url: "https://www.reddit.com/r/GameDesign/",
		category: "社区",
		lang: "en",
		desc: "游戏设计理论/系统/机制讨论子版（网络受限）",
	},
	{
		id: "link-reddit-indiedev",
		title: "Reddit r/IndieDev",
		url: "https://www.reddit.com/r/IndieDev/",
		category: "社区",
		lang: "en",
		desc: "独立游戏开发者交流版，分享进度/寻求反馈（网络受限）",
	},
	{
		id: "link-reddit-gameengines",
		title: "Reddit r/gameengines",
		url: "https://www.reddit.com/r/gameengines/",
		category: "社区",
		lang: "en",
		desc: "自研引擎/引擎选型/渲染技术讨论子版（网络受限）",
	},
	{
		id: "link-reddit-leveldesign",
		title: "Reddit r/leveldesign",
		url: "https://www.reddit.com/r/leveldesign/",
		category: "社区",
		lang: "en",
		desc: "关卡设计交流/展示/反馈子版（网络受限）",
	},
	{
		id: "link-reddit-basebuilding",
		title: "Reddit r/BaseBuildingGames",
		url: "https://www.reddit.com/r/BaseBuildingGames/",
		category: "社区",
		lang: "en",
		desc: "基地建设/殖民模拟类游戏设计与开发讨论（网络受限）",
	},
	{
		id: "link-reddit-4x",
		title: "Reddit r/4Xgaming",
		url: "https://www.reddit.com/r/4Xgaming/",
		category: "社区",
		lang: "en",
		desc: "4X/策略类游戏设计与开发讨论（网络受限）",
	},
	{
		id: "link-reddit-aigamedev",
		title: "Reddit r/aigamedev",
		url: "https://www.reddit.com/r/aigamedev/",
		category: "社区",
		lang: "en",
		desc: "AI 游戏开发/程序化生成技术讨论（网络受限）",
	},
	{
		id: "link-reddit-gameideas",
		title: "Reddit r/gameideas",
		url: "https://www.reddit.com/r/gameideas/",
		category: "社区",
		lang: "en",
		desc: "游戏创意/概念分享与讨论子版（网络受限）",
	},
	{
		id: "link-gamedev-discord",
		title: "Game Dev League",
		url: "https://discord.gg/gamedev",
		category: "社区",
		lang: "en",
		desc: "Discord 上最大的游戏开发者社群，按引擎/工种分频道讨论",
	},
	{
		id: "link-indienova",
		title: "indienova",
		url: "https://indienova.com/",
		category: "社区",
		lang: "zh",
		desc: "中文独立游戏社区，提供资讯/开发日志/游戏素材资源等综合信息",
	},
	{
		id: "link-qiita-game",
		title: "Qiita ゲーム開発",
		url: "https://qiita.com/tags/%E3%82%B2%E3%83%BC%E3%83%A0%E9%96%8B%E7%99%BA",
		category: "社区",
		lang: "ja",
		desc: "日本最大技术博客平台上的游戏开发标签，收录大量 Unity/UE 实战文章",
	},
	{
		id: "link-itchio",
		title: "itch.io",
		url: "https://itch.io/",
		category: "社区",
		lang: "en",
		desc: "最大的独立游戏发布与素材交易平台，海量免费/付费游戏和开发资源",
	},
	{
		id: "link-devtogamedev",
		title: "dev.to #gamedev",
		url: "https://dev.to/t/gamedev",
		category: "社区",
		lang: "en",
		desc: "开发者社区 dev.to 上的游戏开发标签，每日有大量实战经验分享与讨论",
	},
	{
		id: "link-godotshaders",
		title: "Godot Shaders",
		url: "https://godotshaders.com/",
		category: "社区",
		lang: "en",
		desc: "Godot 着色器分享社区，WebGL 实时预览+源码下载，适合学习着色器编程",
	},
	{
		id: "link-mastodon-gamedev",
		title: "GameDev Mastodon",
		url: "https://mastodon.gamedev.place/",
		category: "社区",
		lang: "en",
		desc: "游戏开发者 Mastodon 实例，去中心化社交网络上的活跃开发者社区",
	},
	{
		id: "link-gameres",
		title: "GameRes 游资网",
		url: "https://www.gameres.com/",
		category: "社区",
		lang: "zh",
		desc: "国内知名游戏开发社区，原创教程/资源/问答（网络受限）",
	},

	{
		id: "link-juejin-game",
		title: "掘金 游戏开发",
		url: "https://juejin.cn/tag/%E6%B8%B8%E6%88%8F%E5%BC%80%E5%8F%91",
		category: "社区",
		lang: "zh",
		desc: "掘金技术社区游戏开发标签，国内开发者实战文章（网络受限）",
	},
	{
		id: "link-sf-game",
		title: "SegmentFault 游戏开发",
		url: "https://segmentfault.com/t/%E6%B8%B8%E6%88%8F%E5%BC%80%E5%8F%91",
		category: "社区",
		lang: "zh",
		desc: "SegmentFault 技术社区游戏开发问答/文章（网络受限）",
	},
	{
		id: "link-cnblogs-game",
		title: "博客园 游戏开发",
		url: "https://www.cnblogs.com/cate/gamedev/",
		category: "社区",
		lang: "zh",
		desc: "博客园游戏开发分类，国内程序员的开发经验分享（网络受限）",
	},

	/* ===== 游戏设计/分析 ===== */
	{
		id: "link-gamedesignskills",
		title: "Game Design Skills",
		url: "https://gamedesignskills.com/blog/",
		category: "游戏设计",
		lang: "en",
		desc: "游戏设计百科/文章站，涵盖系统设计/关卡设计/战斗设计/职业发展等主题",
	},
	{
		id: "link-altf4",
		title: "Alt-F4",
		url: "https://alt-f4.blog/zh/",
		category: "游戏设计",
		lang: "zh",
		desc: "Factorio 技术/Mod 分析博客中文版，自动化游戏设计与性能优化深度文章",
	},
	{
		id: "link-rimworld",
		title: "RimWorld",
		url: "https://rimworldgame.com/",
		category: "游戏设计",
		lang: "en",
		desc: "RimWorld 官方开发站，殖民模拟类游戏设计参考（与 Ludeon Studios 互补）",
	},
	{
		id: "link-gh-awesome-game-design",
		title: "awesome-game-design (rafaskb)",
		url: "https://github.com/rafaskb/awesome-game-design",
		category: "游戏设计",
		lang: "en",
		desc: "游戏设计资源合集，设计模式/关卡/UX/叙事等分类",
	},
	{
		id: "link-deepfriedgamer",
		title: "DeepFriedGamer",
		url: "https://deepfriedgamer.com/",
		category: "游戏设计",
		lang: "en",
		desc: "游戏设计理论博客+播客，从基础原理到高级实战的系统化设计讨论",
	},
	{
		id: "link-gamedesignguide",
		title: "Game Design Guide (Substack)",
		url: "https://gamedesignguide.substack.com/",
		category: "游戏设计",
		lang: "en",
		desc: "游戏设计与开发参考指南通讯，涵盖系统设计/原型/迭代方法（Substack 域名受限）",
	},
	{
		id: "link-justingary",
		title: "Think Like A Game Designer",
		url: "https://justingarydesign.substack.com/",
		category: "游戏设计",
		lang: "en",
		desc: "桌游设计师 Justin Gary 的设计思考通讯+播客，每期深度剖析设计方法论（Substack 域名受限）",
	},
	{
		id: "link-videogameworkshop",
		title: "Video Game Workshop",
		url: "https://videogameworkshop.substack.com/",
		category: "游戏设计",
		lang: "en",
		desc: "任天堂风格关卡设计方法论分析，以实际游戏案例拆解关卡设计核心原理（Substack 域名受限）",
	},
	{
		id: "link-scottfine",
		title: "Scott Fine Game Design",
		url: "https://scottfinegamedesign.com/",
		category: "游戏设计",
		lang: "en",
		desc: "游戏设计分析博客，深度拆解 RPG 升级系统/战斗机制/技能设计",
	},
	{
		id: "link-gamescrye",
		title: "GameScrye",
		url: "https://gamescrye.com/",
		category: "游戏设计",
		lang: "en",
		desc: "游戏设计与叙事设计博客，探讨玩家如何沉浸于交互故事的工艺",
	},
	{
		id: "link-gamedesignlevels",
		title: "Game Design Levels (Substack)",
		url: "https://jaimetous.substack.com/",
		category: "游戏设计",
		lang: "en",
		desc: "关卡设计与系统一致性分析，探讨游戏不同系统如何协同工作（Substack 域名受限）",
	},

	/* ===== YouTube 游戏设计频道 ===== */
	{
		id: "link-yt-gmtk",
		title: "Game Maker's Toolkit",
		url: "https://www.youtube.com/@GMTK",
		category: "游戏设计",
		lang: "en",
		desc: "最著名的游戏设计分析频道，Mark Brown 主持，涵盖关卡设计/系统/叙事等深度分析",
	},
	{
		id: "link-yt-designdoc",
		title: "Design Doc",
		url: "https://www.youtube.com/@DesignDoc",
		category: "游戏设计",
		lang: "en",
		desc: "系统化游戏设计论文式分析，每个视频深入剖析一个设计主题",
	},
	{
		id: "link-yt-newframeplus",
		title: "New Frame Plus",
		url: "https://www.youtube.com/@NewFramePlus",
		category: "游戏设计",
		lang: "en",
		desc: "Daniel Floyd 主持的游戏动画设计分析频道，深入解析动画如何影响游戏体验",
	},
	{
		id: "link-yt-aiandgames",
		title: "AI and Games",
		url: "https://www.youtube.com/@AIandGames",
		category: "游戏设计",
		lang: "en",
		desc: "Tommy Thompson 主持，专注 AI 在游戏开发中的应用与实际案例分析",
	},
	{
		id: "link-yt-gdc",
		title: "GDC (Game Developers Conference)",
		url: "https://www.youtube.com/@GDC",
		category: "游戏设计",
		lang: "en",
		desc: "GDC 官方频道，收录历年开发者大会演讲录像，游戏设计/开发/行业全覆盖",
	},
	{
		id: "link-yt-gameoveranalyser",
		title: "Game Overanalyser",
		url: "https://www.youtube.com/@GameOveranalyser",
		category: "游戏设计",
		lang: "en",
		desc: "游戏设计分析频道，以独特视角拆解经典与现代游戏的设计逻辑",
	},
	{
		id: "link-yt-sebastianlague",
		title: "Sebastian Lague",
		url: "https://www.youtube.com/@SebastianLague",
		category: "游戏设计",
		lang: "en",
		desc: "游戏开发/算法/图形学教程频道，交互式可视化编程教学，极高质量",
	},
	{
		id: "link-yt-thinmatrix",
		title: "ThinMatrix",
		url: "https://www.youtube.com/@ThinMatrix",
		category: "游戏设计",
		lang: "en",
		desc: "自研 Java 游戏引擎开发日志，从零搭建 3D 引擎的完整记录",
	},
	{
		id: "link-yt-extracredits",
		title: "Extra Credits",
		url: "https://www.youtube.com/@ExtraCredits",
		category: "游戏设计",
		lang: "en",
		desc: "游戏设计历史与理论系列，深入浅出的教育内容（已停止更新但仍有参考价值）",
	},

	/* ===== B站游戏设计UP主 ===== */
	{
		id: "link-bili-indienova",
		title: "indienova B站频道",
		url: "https://space.bilibili.com/25676644",
		category: "社区",
		lang: "zh",
		desc: "indienova 独立游戏官方 B 站账号，分享独立游戏开发/设计视频内容",
	},

	/* ===== 知乎专栏 ===== */
	{
		id: "link-zhihu-columb",
		title: "系统策划必看（知乎专栏）",
		url: "https://zhuanlan.zhihu.com/p/22359562816",
		category: "游戏设计",
		lang: "zh",
		desc: "知乎专栏，系统化拆解游戏系统设计方法论的实战文章",
	},
	{
		id: "link-zhihu-leveldesign",
		title: "游戏设计集·关卡设计（知乎专栏）",
		url: "https://zhuanlan.zhihu.com/p/457342254",
		category: "叙事/关卡/UX",
		lang: "zh",
		desc: "编译《The Level Design Book》核心章节的中文关卡设计系列",
	},
	{
		id: "link-zhihu-gdd",
		title: "Game Design and Development（知乎专栏）",
		url: "https://zhuanlan.zhihu.com/p/60545558",
		category: "游戏设计",
		lang: "zh",
		desc: "游戏设计全流程理论与实践的知乎专栏",
	},
	{
		id: "link-numeric-planner",
		title: "游戏数值策划完全教程",
		url: "https://zsc.github.io/numeric_planner_tutorial/",
		category: "游戏设计",
		lang: "zh",
		desc: "GitHub Pages 上的数值策划/经济系统开放教程，从街机到大型游戏的数值设计",
	},

	/* ===== 游戏行业/演讲 ===== */
	{
		id: "link-gdc",
		title: "GDC Vault",
		url: "https://www.gdconf.com/",
		category: "行业/商业",
		lang: "en",
		desc: "游戏开发者大会演讲录像与幻灯片，了解游戏工业最新实践的第一现场",
	},
	{
		id: "link-gamedeveloper",
		title: "Game Developer",
		url: "https://www.gamedeveloper.com/",
		category: "行业/商业",
		lang: "en",
		desc: "原 Gamasutra，游戏行业深度分析与技术文章，覆盖面最广的行业媒体（部分网络受限）",
	},

	/* ===== 游戏商业/发行 ===== */
	{
		id: "link-gameassemly",
		title: "Game Dev Assembly (Substack)",
		url: "https://gamedevnewsletter.substack.com/",
		category: "行业/商业",
		lang: "en",
		desc: "游戏开发营销/商业策略通讯，覆盖发行/增长/全球化等实务话题（Substack 域名受限）",
	},

	/* ===== 游戏编程/架构 ===== */
	{
		id: "link-gp-patterns",
		title: "Game Programming Patterns",
		url: "https://gameprogrammingpatterns.com/",
		category: "编程/技术",
		lang: "en",
		desc: "游戏编程设计模式在线全书，涵盖命令/观察者/对象池/状态机等经典模式",
	},
	{
		id: "link-redblob",
		title: "Red Blob Games",
		url: "https://www.redblobgames.com/",
		category: "编程/技术",
		lang: "en",
		desc: "交互式可视化游戏算法教程，A* 寻路/六边形网格/程序化生成等",
	},
	{
		id: "link-generalistprogrammer",
		title: "Generalist Programmer",
		url: "https://generalistprogrammer.com/",
		category: "编程/技术",
		lang: "en",
		desc: "游戏开发编程教程站，涵盖 Unity/Unreal/C#/C++ 及游戏设计模式",
	},
	{
		id: "link-lazyfoo",
		title: "Lazy Foo' SDL",
		url: "https://lazyfoo.net/",
		category: "编程/技术",
		lang: "en",
		desc: "SDL 2D 游戏编程入门教程，从窗口创建到粒子系统，完整 C++ 指南",
	},

	/* ===== 图形/渲染编程 ===== */
	{
		id: "link-learnopengl",
		title: "Learn OpenGL",
		url: "https://learnopengl.com/",
		category: "编程/技术",
		lang: "en",
		desc: "现代 OpenGL 图形编程入门教程，从 shader 到 PBR 渲染一应俱全",
	},
	{
		id: "link-pikuma",
		title: "Pikuma",
		url: "https://pikuma.com/",
		category: "编程/技术",
		lang: "en",
		desc: "游戏数学/物理/图形学底层原理教程，从零实现软渲染器和游戏引擎",
	},

	/* ===== 程序化生成 ===== */
	{
		id: "link-pcgwiki",
		title: "PCG Wiki",
		url: "https://pcg.wikidot.com/",
		category: "编程/技术",
		lang: "en",
		desc: "程序化生成 Wiki，算法分类+游戏目录+学术资源索引，PCG 领域最全知识库",
	},

	/* ===== 叙事/对话工具 ===== */
	{
		id: "link-ink",
		title: "Ink (inkle)",
		url: "https://www.inklestudios.com/ink/",
		category: "叙事/关卡/UX",
		lang: "en",
		desc: "开源叙事脚本语言，被 80 Days / Heaven's Vault 等大量独立游戏使用",
	},
	{
		id: "link-yarnspinner",
		title: "Yarn Spinner",
		url: "https://yarnspinner.dev/",
		category: "叙事/关卡/UX",
		lang: "en",
		desc: "对话系统工具，VS Code 编辑器+语法高亮+预览，集成 Unity/Godot",
	},
	{
		id: "link-twine",
		title: "Twine",
		url: "https://twinery.org/",
		category: "叙事/关卡/UX",
		lang: "en",
		desc: "开源非线性叙事/互动小说创作工具，可视化分支故事编辑器",
	},
	{
		id: "link-storyflow-editor",
		title: "StoryFlow Editor",
		url: "https://storyflow-editor.com/",
		category: "叙事/关卡/UX",
		lang: "en",
		desc: "节点式对话编辑器，支持 Unity/Unreal/Godot，开源 MIT 许可",
	},
	{
		id: "link-newtonarrative",
		title: "New to Narrative",
		url: "https://newtonarrative.com/",
		category: "叙事/关卡/UX",
		lang: "en",
		desc: "叙事设计教程站，从零开始学游戏叙事，涵盖角色/情节/世界观/分支故事",
	},
	{
		id: "link-narrativedesigner",
		title: "NarrativeDesigner.com",
		url: "https://www.narrativedesigner.com/",
		category: "叙事/关卡/UX",
		lang: "en",
		desc: "叙事设计全流程参考站，从大纲到对话树的方法论与模板",
	},
	{
		id: "link-narrativenews",
		title: "Narrative News (Substack)",
		url: "https://narrativenews.substack.com/",
		category: "叙事/关卡/UX",
		lang: "en",
		desc: "游戏叙事设计月报，汇总资源/职位/活动/访谈（Substack 域名受限）",
	},
	{
		id: "link-narrativedesign-substack",
		title: "Narrative Design (Substack)",
		url: "https://narrativedesign.substack.com/",
		category: "叙事/关卡/UX",
		lang: "en",
		desc: "游戏叙事设计深度分析，从 Chrono Trigger 到现代分支叙事的演变（Substack 域名受限）",
	},
	{
		id: "link-pietronarrative",
		title: "Around Narrative Design (Substack)",
		url: "https://peterpunk.substack.com/",
		category: "叙事/关卡/UX",
		lang: "en",
		desc: "Pietro Polsinelli 的叙事设计研究，涵盖视频/桌游/应用游戏叙事（Substack 域名受限）",
	},

	/* ===== 关卡设计 ===== */
	{
		id: "link-leveldesignbook",
		title: "The Level Design Book",
		url: "https://book.leveldesignbook.com/",
		category: "叙事/关卡/UX",
		lang: "en",
		desc: "关卡设计在线全书，从预制作到光照的完整流程指南，含中文翻译",
	},
	{
		id: "link-leveldesignorg",
		title: "LEVEL-DESIGN.org",
		url: "https://level-design.org/",
		category: "叙事/关卡/UX",
		lang: "en",
		desc: "500+ 游戏关卡截图参考数据库，按游戏/类型检索关卡布局与结构",
	},
	{
		id: "link-worldofleveldesign",
		title: "World of Level Design",
		url: "https://www.worldofleveldesign.com/",
		category: "叙事/关卡/UX",
		lang: "en",
		desc: "UE/Unity/Blender 关卡设计实战教程，涵盖光效/地形/性能优化",
	},
	{
		id: "link-leveldesignbook-cn",
		title: "关卡设计指南（中文版）",
		url: "https://book.leveldesignbook.cn/",
		category: "叙事/关卡/UX",
		lang: "zh",
		desc: "《The Level Design Book》中文译本，涵盖关卡制作全流程与经验分享",
	},

	/* ===== 世界观设计 ===== */
	{
		id: "link-chaoticanwriter",
		title: "Chaotican Writer",
		url: "https://chaoticanwriter.com/",
		category: "叙事/关卡/UX",
		lang: "en",
		desc: "世界观/TTRPG/奇幻科幻写作博客，从零构建可信世界的系统方法",
	},
	{
		id: "link-chapterpub-worldbuilding",
		title: "Chapter Pub 世界观指南",
		url: "https://blog.chapter.pub/",
		category: "叙事/关卡/UX",
		lang: "en",
		desc: "世界观创作完整指南，涵盖地理/文化/魔法/政治/历史的系统化构建",
	},
	{
		id: "link-savameta",
		title: "Sava Meta",
		url: "https://savameta.com/",
		category: "叙事/关卡/UX",
		lang: "en",
		desc: "游戏叙事与世界观设计博客，探讨故事如何在交互媒介中发挥作用",
	},

	/* ===== UI/UX 设计 ===== */
	{
		id: "link-gameuidatabase",
		title: "Game UI Database",
		url: "https://www.gameuidatabase.com/",
		category: "叙事/关卡/UX",
		lang: "en",
		desc: "1800+ 游戏、73000+ 截图 UI 参考库，按屏幕类型/交互模式检索",
	},

	/* ===== 游戏框架/引擎 ===== */
	{
		id: "link-monogame",
		title: "MonoGame",
		url: "https://www.monogame.net/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "跨平台 .NET 游戏框架，Stardew Valley / Celeste 等名作的技术底座",
	},
	{
		id: "link-ogre3d",
		title: "Ogre3D",
		url: "https://www.ogre3d.org/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "开源 3D 渲染引擎，C++ 编写，拥有丰富的文档/论坛/插件生态",
	},
	{
		id: "link-gh-awesome-game-engines",
		title: "awesome-game-engines (brandonhimpfen)",
		url: "https://github.com/brandonhimpfen/awesome-game-engines",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "游戏引擎/框架汇总列表，覆盖 2D/3D/VR",
	},
	{
		id: "link-fyrox",
		title: "Fyrox",
		url: "https://fyrox.rs/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "Rust 开源 3D 游戏引擎，功能完整的现代引擎",
	},
	{
		id: "link-gdevelop",
		title: "GDevelop 中文",
		url: "https://gdevelop.io/zh-cn/",
		category: "游戏框架/引擎",
		lang: "zh",
		desc: "开源零代码游戏引擎，支持 2D/3D，AI 辅助开发，适合快速原型和教学",
	},
	{
		id: "link-unrealengine",
		title: "Unreal Engine",
		url: "https://www.unrealengine.com/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "Epic Games 开发的 AAA 级 3D 引擎，C++/蓝图双模式，影视虚拟制片首选",
	},
	{
		id: "link-unrealengine-cn",
		title: "Unreal Engine 中文站",
		url: "https://www.unrealengine.com/zh-CN/",
		category: "游戏框架/引擎",
		lang: "zh",
		desc: "虚幻引擎中文官方站点，含中文文档/案例/社区",
	},
	{
		id: "link-unrealsource",
		title: "UnrealSource",
		url: "https://unrealsource.com/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "Unreal Engine 独立新闻通讯，每期汇总引擎更新/插件/技巧",
	},
	{
		id: "link-unity",
		title: "Unity",
		url: "https://unity.com/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "全球最普及的 2D/3D 游戏引擎，C# 语言，移动端开发绝对主力",
	},
	{
		id: "link-unity-cn",
		title: "Unity 中文官网",
		url: "https://unity.cn/",
		category: "游戏框架/引擎",
		lang: "zh",
		desc: "Unity 中国官方站，含中文学习资源/社区/案例",
	},
	{
		id: "link-godot",
		title: "Godot Engine",
		url: "https://godotengine.org/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "MIT 开源 2D/3D 游戏引擎，节点化架构+GDScript/C#/C++ 多语言",
	},
	{
		id: "link-godot-cn",
		title: "Godot 中国站",
		url: "https://www.godot-cn.com/",
		category: "游戏框架/引擎",
		lang: "zh",
		desc: "Godot 中文社区站点，中文文档翻译/教程/问答",
	},
	{
		id: "link-godothub",
		title: "GodotHub",
		url: "https://godothub.com/",
		category: "游戏框架/引擎",
		lang: "zh",
		desc: "国内 Godot 游戏引擎社区服务平台，教程/资源/问答",
	},
	{
		id: "link-godotfoundry",
		title: "Godot Foundry",
		url: "https://godotfoundry.com/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "Godot 引擎教程站，含着色器分解/GDScript 教程/资源指南",
	},
	{
		id: "link-bevy",
		title: "Bevy Engine",
		url: "https://bevyengine.org/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "Rust 编写的 ECS 架构游戏引擎，数据驱动+快编译+零依赖",
	},
	{
		id: "link-flax",
		title: "Flax Engine",
		url: "https://flaxengine.com/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "C# 3D 游戏引擎，Vulkan/渲染管线友好，编辑器体验流畅",
	},
	{
		id: "link-defold",
		title: "Defold",
		url: "https://defold.com/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "跨平台 2D 游戏引擎，Lua 脚本，轻量快速，King（糖果粉碎）出品",
	},
	{
		id: "link-cocos",
		title: "Cocos Creator",
		url: "https://www.cocos.com/",
		category: "游戏框架/引擎",
		lang: "zh",
		desc: "国产 2D/3D 游戏引擎，TypeScript 脚本，小游戏/H5 领域王者",
	},
	{
		id: "link-playcanvas",
		title: "PlayCanvas",
		url: "https://playcanvas.com/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "开源 WebGL/WebGPU 3D 引擎，浏览器内编辑+发布",
	},
	{
		id: "link-phaser",
		title: "Phaser",
		url: "https://phaser.io/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "最流行的 HTML5 2D 游戏框架，JavaScript/TypeScript，活跃社区",
	},
	{
		id: "link-panda3d",
		title: "Panda3D",
		url: "https://www.panda3d.org/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "迪士尼/卡内基梅隆维护的 3D 引擎，Python/C++ 双语言",
	},
	{
		id: "link-love2d",
		title: "LÖVE",
		url: "https://love2d.org/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "Lua 驱动的 2D 游戏框架，极简 API + 原生性能，快速原型利器",
	},
	{
		id: "link-gamemaker",
		title: "GameMaker",
		url: "https://gamemaker.io/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "YoYo Games 出品的 2D 游戏引擎，GML 语言+DnD 可视化编程",
	},
	{
		id: "link-construct",
		title: "Construct",
		url: "https://www.construct.net/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "可视化事件表驱动的 2D 游戏引擎，无需代码，浏览器在线编辑",
	},
	{
		id: "link-stride",
		title: "Stride 3D",
		url: "https://www.stride3d.net/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "开源 C# 3D 引擎（原 Xenko），.NET 生态+多平台导出+编辑器",
	},
	{
		id: "link-ambient",
		title: "Ambient",
		url: "https://ambient.run/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "Rust 编写的 Web 优先 3D 引擎，无运行时依赖，浏览器内运行",
	},
	{
		id: "link-machengine",
		title: "Mach Engine",
		url: "https://machengine.org/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "Zig 编写的模块化游戏引擎，GPU 优先，零开销抽象",
	},
	{
		id: "link-haxeflixel",
		title: "HaxeFlixel",
		url: "https://haxeflixel.com/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "Haxe 跨平台 2D 游戏框架，类 Flixel API，一次编写处处运行",
	},
	{
		id: "link-renpy",
		title: "Ren'Py",
		url: "https://www.renpy.org/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "视觉小说引擎，Python 脚本，全球最流行的 ADV 创作工具",
	},
	{
		id: "link-cocos2dx",
		title: "Cocos2d-x",
		url: "https://www.cocos2d-x.org/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "老牌 C++ 2D 引擎，跨平台+开源，曾是国内移动游戏开发第一选择",
	},
	{
		id: "link-solar2d",
		title: "Solar2D",
		url: "https://solar2d.com/",
		category: "游戏框架/引擎",
		lang: "en",
		desc: "Lua 驱动的 2D 引擎（原 Corona SDK），快速原型+物理引擎集成",
	},

	/* ===== CI/CD 与构建 ===== */
	{
		id: "link-gameci",
		title: "Game CI",
		url: "https://game.ci/",
		category: "编程/技术",
		lang: "en",
		desc: "游戏 CI/CD 工具集，GitHub Actions 集成 Unity/Godot/Unreal 自动构建",
	},

	/* ===== 素材资源 ===== */
	{
		id: "link-opengameart",
		title: "OpenGameArt",
		url: "https://opengameart.org/",
		category: "资源/工具",
		lang: "en",
		desc: "最大的免费游戏美术库，含精灵/纹理/模型/音效，多种 CC 许可证",
	},
	{
		id: "link-freesound",
		title: "Freesound",
		url: "https://freesound.org/",
		category: "资源/工具",
		lang: "en",
		desc: "CC 许可音效共享平台，收录数万条真实世界录音和合成音效片段",
	},
	{
		id: "link-game-icons",
		title: "Game-Icons.net",
		url: "https://game-icons.net/",
		category: "资源/工具",
		lang: "en",
		desc: "数千款免费可商用游戏 SVG 图标，支持按颜色/大小批量导出",
	},
	{
		id: "link-kenney",
		title: "Kenney Assets",
		url: "https://kenney.nl/",
		category: "资源/工具",
		lang: "en",
		desc: "高质量免费游戏素材包（CC0），涵盖 UI/图标/角色/环境/字体等",
	},
	{
		id: "link-textures",
		title: "Textures.com",
		url: "https://www.textures.com/",
		category: "资源/工具",
		lang: "en",
		desc: "海量 PBR 材质贴图库，涵盖各类地面/墙面/金属/木纹等游戏材质",
	},
	{
		id: "link-itchio-assets",
		title: "itch.io 素材区",
		url: "https://itch.io/game-assets",
		category: "资源/工具",
		lang: "en",
		desc: "独立开发者交易平台，数千款付费/免费游戏素材涵盖 2D/3D/音频/代码",
	},

	/* ===== 音频工具 ===== */
	{
		id: "link-lmms",
		title: "LMMS",
		url: "https://lmms.io/",
		category: "资源/工具",
		lang: "en",
		desc: "开源数字音频工作站（DAW），支持 MIDI/VST/LADSPA，可制作游戏配乐",
	},
	{
		id: "link-audacity",
		title: "Audacity",
		url: "https://www.audacityteam.org/",
		category: "资源/工具",
		lang: "en",
		desc: "免费开源音频录制 & 多轨编辑，用于游戏音效剪辑/去噪/格式转换",
	},
	{
		id: "link-boscaceoil",
		title: "Bosca Ceoil",
		url: "https://boscaceoil.net/",
		category: "资源/工具",
		lang: "en",
		desc: "蓝调音乐作曲工具，初学者友好，可快速生成循环背景音乐旋律",
	},
	{
		id: "link-sfxr",
		title: "sfxr / jsfxr",
		url: "https://sfxr.me/",
		category: "资源/工具",
		lang: "en",
		desc: "在线 8bit/16bit 游戏音效生成器，调节参数即时试听并导出 WAV",
	},
	{
		id: "link-musescore",
		title: "MuseScore",
		url: "https://musescore.org/",
		category: "资源/工具",
		lang: "en",
		desc: "开源乐谱编辑器，可谱写 MIDI 并导出为音频文件或印刷式乐谱 PDF",
	},

	/* ===== 图形/美术工具（最静态） ===== */
	{
		id: "link-aseprite",
		title: "Aseprite",
		url: "https://www.aseprite.org/",
		category: "资源/工具",
		lang: "en",
		desc: "专业的像素画 & 精灵动图编辑器，支持图层/帧动画/调色板，Steam 有售",
	},
	{
		id: "link-tiled",
		title: "Tiled",
		url: "https://www.mapeditor.org/",
		category: "资源/工具",
		lang: "en",
		desc: "免费灵活的 2D 网格地图编辑器，支持正交/等距/六边形地图，多引擎导出",
	},
	{
		id: "link-spine",
		title: "Spine",
		url: "http://esotericsoftware.com/",
		category: "资源/工具",
		lang: "en",
		desc: "2D 骨骼动画编辑器，被 Unity/UE/Godot/Cocos 等主流引擎广泛集成",
	},
	{
		id: "link-texturepacker",
		title: "TexturePacker",
		url: "https://www.codeandweb.com/texturepacker",
		category: "资源/工具",
		lang: "en",
		desc: "Sprite 帧图打包 & 图集优化工具，支持 Unity/UE/Cocos/Phaser 等引擎导出",
	},
	{
		id: "link-pyxeledit",
		title: "PyxelEdit",
		url: "http://pyxeledit.com/",
		category: "资源/工具",
		lang: "en",
		desc: "专为像素画设计的编辑器，内置瓷砖地图编辑 & 逐帧动画功能",
	},
	{
		id: "link-piskel",
		title: "Piskel",
		url: "https://www.piskelapp.com/",
		category: "资源/工具",
		lang: "en",
		desc: "免费在线像素画编辑器，无需安装即可制作精灵图和逐帧动画",
	},
	{
		id: "link-blender",
		title: "Blender",
		url: "https://www.blender.org/",
		category: "资源/工具",
		lang: "en",
		desc: "开源 3D 建模/雕刻/材质/动画/渲染/合成全流程，游戏资产管线标配",
	},
	{
		id: "link-krita",
		title: "Krita",
		url: "https://krita.org/",
		category: "资源/工具",
		lang: "en",
		desc: "开源数字绘画软件，笔刷引擎强大，适合游戏概念设计与材质贴图绘制",
	},

	/* ===== 通用开发工具 ===== */
	{
		id: "link-zed",
		title: "Zed Editor",
		url: "https://zed.dev/blog",
		category: "编程/技术",
		lang: "en",
		desc: "高性能 Rust 代码编辑器，Atom/树型游标原班人马打造，内置 AI 与协作",
	},
	{
		id: "link-gh-awesome-gamedev-magic",
		title: "magictools (ellisonleao)",
		url: "https://github.com/ellisonleao/magictools",
		category: "编程/技术",
		lang: "en",
		desc: "游戏开发资源大全，覆盖图形/代码/音频/设计等，13k+ stars",
	},
	{
		id: "link-gh-awesome-gamedev-skywind",
		title: "awesome-gamedev (skywind3000)",
		url: "https://github.com/skywind3000/awesome-gamedev",
		category: "编程/技术",
		lang: "en",
		desc: "中文维护的游戏开发资源列表，引擎/工具/教程齐全",
	},
	{
		id: "link-gh-awesome-gamedev-calinou",
		title: "awesome-gamedev (Calinou)",
		url: "https://github.com/Calinou/awesome-gamedev",
		category: "编程/技术",
		lang: "en",
		desc: "仅收录自由/开源软件的游戏开发资源列表",
	},
	{
		id: "link-gh-gamedev-resources",
		title: "GameDev-Resources (Kavex)",
		url: "https://github.com/Kavex/GameDev-Resources",
		category: "编程/技术",
		lang: "en",
		desc: "按资产/代码/设计/工具分类的游戏开发资源集",
	},
	{
		id: "link-gh-awesome-game-engine-dev",
		title: "awesome-game-engine-dev (stevinz)",
		url: "https://github.com/stevinz/awesome-game-engine-dev",
		category: "编程/技术",
		lang: "en",
		desc: "游戏引擎开发资源专精，架构/渲染/物理等分类",
	},
	{
		id: "link-gh-awesome-gamedev-fronkon",
		title: "Awesome-Gamedev (FronkonGames)",
		url: "https://github.com/FronkonGames/Awesome-Gamedev",
		category: "编程/技术",
		lang: "en",
		desc: "代码/工具/教程分类清晰的游戏开发资源合集",
	},
	{
		id: "link-gh-awesome-open-source-games",
		title: "awesome-open-source-games (michelpereira)",
		url: "https://github.com/michelpereira/awesome-open-source-games",
		category: "编程/技术",
		lang: "en",
		desc: "开源游戏源码合集，可学习完整项目开发，15k+ stars",
	},
	// Ollama 和 Anthropic Engineering Blog 已移除（不直接相关游戏开发）
	{
		id: "link-renderdoc",
		title: "RenderDoc",
		url: "https://renderdoc.org/",
		category: "编程/技术",
		lang: "en",
		desc: "开源 GPU 调试器，抓帧分析渲染管线，游戏图形调试标配工具",
	},
	{
		id: "link-gimp",
		title: "GIMP",
		url: "https://www.gimp.org/",
		category: "资源/工具",
		lang: "en",
		desc: "开源图像编辑软件，功能接近 Photoshop，适合贴图编辑与概念图",
	},
	{
		id: "link-material-maker",
		title: "Material Maker",
		url: "https://www.materialmaker.org/",
		category: "资源/工具",
		lang: "en",
		desc: "开源节点式 PBR 材质生成工具，类似 Substance Designer，可导出到 Godot/UE",
	},
	/* ===== 新闻源 ===== */
	{
		id: "src-aiandgames",
		title: "AI and Games",
		url: "https://www.aiandgames.com",
		category: "社区",
		lang: "en",
		desc: "AI and Games 提供的最新游戏开发资讯",
	},
	{
		id: "src-flaxengine",
		title: "Flax Engine",
		url: "https://flaxengine.com",
		category: "社区",
		lang: "en",
		desc: "Flax Engine 提供的最新游戏开发资讯",
	},
	{
		id: "src-gamedevacademy",
		title: "GameDev Academy",
		url: "https://gamedevacademy.org",
		category: "博客",
		lang: "en",
		desc: "GameDev Academy 提供的最新游戏开发资讯",
	},
	{
		id: "src-鵺游戏设计",
		title: "鵺 游戏设计",
		url: "https://www.cnblogs.com/lxz-notebook",
		category: "博客",
		lang: "zh",
		desc: "鵺 游戏设计 提供的最新游戏开发资讯",
	},
	{
		id: "src-indienova独立游戏",
		title: "Indienova 独立游戏",
		url: "https://indienova.com",
		category: "社区",
		lang: "zh",
		desc: "Indienova 独立游戏 提供的最新游戏开发资讯",
	},
	{
		id: "src-4gamernet",
		title: "4Gamer.net",
		url: "https://www.4gamer.net",
		category: "社区",
		lang: "ja",
		desc: "4Gamer.net 提供的最新游戏开发资讯",
	},
	{
		id: "src-aiming開発者",
		title: "Aiming 開発者ブログ",
		url: "https://developer.aiming-inc.com",
		category: "社区",
		lang: "ja",
		desc: "Aiming 開発者ブログ 提供的最新游戏开发资讯",
	},
	{
		id: "src-applibottech",
		title: "Applibot Tech",
		url: "https://tech.applibot.co.jp",
		category: "社区",
		lang: "ja",
		desc: "Applibot Tech 提供的最新游戏开发资讯",
	},
	{
		id: "src-gamecodingclassics",
		title: "Game Coding Classics",
		url: "https://hysblog.com",
		category: "博客",
		lang: "ja",
		desc: "Game Coding Classics 提供的最新游戏开发资讯",
	},
	{
		id: "src-greetech",
		title: "GREE Tech",
		url: "https://labs.gree.jp",
		category: "社区",
		lang: "ja",
		desc: "GREE Tech 提供的最新游戏开发资讯",
	},
	{
		id: "src-igdajapan",
		title: "IGDA Japan",
		url: "https://igda.jp",
		category: "社区",
		lang: "ja",
		desc: "IGDA Japan 提供的最新游戏开发资讯",
	},
	{
		id: "src-indiegamesjpdev",
		title: "IndieGamesJp.dev",
		url: "https://indiegamesjp.dev",
		category: "社区",
		lang: "ja",
		desc: "IndieGamesJp.dev 提供的最新游戏开发资讯",
	},
	{
		id: "src-kayactechblog",
		title: "KAYAC Tech Blog",
		url: "https://techblog.kayac.com",
		category: "社区",
		lang: "ja",
		desc: "KAYAC Tech Blog 提供的最新游戏开发资讯",
	},
	{
		id: "src-qiitagameai",
		title: "Qiita game AI",
		url: "https://qiita.com",
		category: "社区",
		lang: "ja",
		desc: "Qiita game AI 提供的最新游戏开发资讯",
	},
	{
		id: "src-qiitagodot",
		title: "Qiita Godot",
		url: "https://qiita.com",
		category: "社区",
		lang: "ja",
		desc: "Qiita Godot 提供的最新游戏开发资讯",
	},
	{
		id: "src-qiitaunity",
		title: "Qiita Unity",
		url: "https://qiita.com",
		category: "社区",
		lang: "ja",
		desc: "Qiita Unity 提供的最新游戏开发资讯",
	},
	{
		id: "src-qiitaunrealengine",
		title: "Qiita UnrealEngine",
		url: "https://qiita.com",
		category: "社区",
		lang: "ja",
		desc: "Qiita UnrealEngine 提供的最新游戏开发资讯",
	},
	{
		id: "src-qiita開発",
		title: "Qiita ゲーム開発",
		url: "https://qiita.com",
		category: "社区",
		lang: "ja",
		desc: "Qiita ゲーム開発 提供的最新游戏开发资讯",
	},
	{
		id: "src-qiita",
		title: "Qiita ゲームデザイン",
		url: "https://qiita.com",
		category: "社区",
		lang: "ja",
		desc: "Qiita ゲームデザイン 提供的最新游戏开发资讯",
	},
	{
		id: "src-segatechblog",
		title: "SEGA Tech Blog",
		url: "https://techblog.sega.jp",
		category: "社区",
		lang: "ja",
		desc: "SEGA Tech Blog 提供的最新游戏开发资讯",
	},
	{
		id: "src-zenn创作",
		title: "Zenn 创作",
		url: "https://zenn.dev",
		category: "社区",
		lang: "ja",
		desc: "Zenn 创作 提供的最新游戏开发资讯",
	},
	{
		id: "src-zenn写作",
		title: "Zenn 写作",
		url: "https://zenn.dev",
		category: "社区",
		lang: "ja",
		desc: "Zenn 写作 提供的最新游戏开发资讯",
	},
	{
		id: "src-zenn游戏设计",
		title: "Zenn 游戏设计",
		url: "https://zenn.dev",
		category: "社区",
		lang: "ja",
		desc: "Zenn 游戏设计 提供的最新游戏开发资讯",
	},
	{
		id: "src-zenn游戏引擎",
		title: "Zenn 游戏引擎",
		url: "https://zenn.dev",
		category: "社区",
		lang: "ja",
		desc: "Zenn 游戏引擎 提供的最新游戏开发资讯",
	},
	{
		id: "src-zennbevy",
		title: "Zenn Bevy",
		url: "https://zenn.dev",
		category: "社区",
		lang: "ja",
		desc: "Zenn Bevy 提供的最新游戏开发资讯",
	},
	{
		id: "src-zenngamedev",
		title: "Zenn gamedev",
		url: "https://zenn.dev",
		category: "社区",
		lang: "ja",
		desc: "Zenn gamedev 提供的最新游戏开发资讯",
	},
	{
		id: "src-zenngodot",
		title: "Zenn Godot",
		url: "https://zenn.dev",
		category: "社区",
		lang: "ja",
		desc: "Zenn Godot 提供的最新游戏开发资讯",
	},
	{
		id: "src-zennuiux",
		title: "Zenn UI/UX",
		url: "https://zenn.dev",
		category: "社区",
		lang: "ja",
		desc: "Zenn UI/UX 提供的最新游戏开发资讯",
	},
	{
		id: "src-zennuiux设计",
		title: "Zenn UIUX设计",
		url: "https://zenn.dev",
		category: "社区",
		lang: "ja",
		desc: "Zenn UIUX设计 提供的最新游戏开发资讯",
	},
	{
		id: "src-zennunity",
		title: "Zenn Unity",
		url: "https://zenn.dev",
		category: "社区",
		lang: "ja",
		desc: "Zenn Unity 提供的最新游戏开发资讯",
	},
	{
		id: "src-zennunrealengine",
		title: "Zenn UnrealEngine",
		url: "https://zenn.dev",
		category: "社区",
		lang: "ja",
		desc: "Zenn UnrealEngine 提供的最新游戏开发资讯",
	},
	{
		id: "src-24indie",
		title: "24indie",
		url: "https://24indie.com",
		category: "社区",
		lang: "en",
		desc: "24indie 提供的最新游戏开发资讯",
	},
	{
		id: "src-80level",
		title: "80 Level",
		url: "https://80.lv",
		category: "社区",
		lang: "en",
		desc: "80 Level 提供的最新游戏开发资讯",
	},
	{
		id: "src-alanzucconi",
		title: "Alan Zucconi",
		url: "https://www.alanzucconi.com",
		category: "博客",
		lang: "en",
		desc: "Alan Zucconi 提供的最新游戏开发资讯",
	},
	{
		id: "src-amdgpuopen",
		title: "AMD GPUOpen",
		url: "https://gpuopen.com",
		category: "社区",
		lang: "en",
		desc: "AMD GPUOpen 提供的最新游戏开发资讯",
	},
	{
		id: "src-asepriteblog",
		title: "Aseprite Blog",
		url: "https://aseprite.org",
		category: "社区",
		lang: "en",
		desc: "Aseprite Blog 提供的最新游戏开发资讯",
	},
	{
		id: "src-bevyengine",
		title: "Bevy Engine",
		url: "https://bevyengine.org",
		category: "社区",
		lang: "en",
		desc: "Bevy Engine 提供的最新游戏开发资讯",
	},
	{
		id: "src-blenderdevblog",
		title: "Blender Dev Blog",
		url: "https://www.blender.org/development",
		category: "社区",
		lang: "en",
		desc: "Blender Dev Blog 提供的最新游戏开发资讯",
	},
	{
		id: "src-blendernews",
		title: "Blender News",
		url: "https://www.blender.org",
		category: "社区",
		lang: "en",
		desc: "Blender News 提供的最新游戏开发资讯",
	},
	{
		id: "src-caniplaythat",
		title: "Can I Play That?",
		url: "https://caniplaythat.com",
		category: "博客",
		lang: "en",
		desc: "Can I Play That? 提供的最新游戏开发资讯",
	},
	{
		id: "src-cannibalhalfling",
		title: "Cannibal Halfling",
		url: "https://cannibalhalflinggaming.com",
		category: "博客",
		lang: "en",
		desc: "Cannibal Halfling 提供的最新游戏开发资讯",
	},
	{
		id: "src-captainofindustry",
		title: "Captain of Industry",
		url: "https://www.captainofindustry.com",
		category: "博客",
		lang: "en",
		desc: "Captain of Industry 提供的最新游戏开发资讯",
	},
	{
		id: "src-catnapgames",
		title: "Catnap Games",
		url: "https://catnapgames.com",
		category: "博客",
		lang: "en",
		desc: "Catnap Games 提供的最新游戏开发资讯",
	},
	{
		id: "src-chaoticanwriter",
		title: "Chaotican Writer",
		url: "https://www.chaoticanwriter.com",
		category: "博客",
		lang: "en",
		desc: "Chaotican Writer 提供的最新游戏开发资讯",
	},
	{
		id: "src-danfelder",
		title: "Dan Felder",
		url: "https://danfelder.net",
		category: "博客",
		lang: "en",
		desc: "Dan Felder 提供的最新游戏开发资讯",
	},
	{
		id: "src-defoldengine",
		title: "Defold Engine",
		url: "https://defold.com",
		category: "社区",
		lang: "en",
		desc: "Defold Engine 提供的最新游戏开发资讯",
	},
	{
		id: "src-frictionalgames",
		title: "Frictional Games",
		url: "https://frictionalgames.com",
		category: "博客",
		lang: "en",
		desc: "Frictional Games 提供的最新游戏开发资讯",
	},
	{
		id: "src-gamedevessentials",
		title: "Game Dev Essentials",
		url: "https://gamedevessentials.com",
		category: "博客",
		lang: "en",
		desc: "Game Dev Essentials 提供的最新游戏开发资讯",
	},
	{
		id: "src-gamewisdom",
		title: "Game Wisdom",
		url: "https://gamewisdom.com",
		category: "博客",
		lang: "en",
		desc: "Game Wisdom 提供的最新游戏开发资讯",
	},
	{
		id: "src-gamedevunchained",
		title: "Gamedev Unchained",
		url: "https://gamedevunchained.com",
		category: "博客",
		lang: "en",
		desc: "Gamedev Unchained 提供的最新游戏开发资讯",
	},
	{
		id: "src-gamesbymason",
		title: "Games by Mason",
		url: "https://gamesbymason.com",
		category: "博客",
		lang: "en",
		desc: "Games by Mason 提供的最新游戏开发资讯",
	},
	{
		id: "src-gamesindustrybiz",
		title: "GamesIndustry.biz",
		url: "https://www.gamesindustry.biz",
		category: "社区",
		lang: "en",
		desc: "GamesIndustry.biz 提供的最新游戏开发资讯",
	},
	{
		id: "src-gameworldobserver",
		title: "GameWorld Observer",
		url: "https://gameworldobserver.com",
		category: "博客",
		lang: "en",
		desc: "GameWorld Observer 提供的最新游戏开发资讯",
	},
	{
		id: "src-generativegamedev",
		title: "Generative GameDev",
		url: "https://generativegamedev.com",
		category: "博客",
		lang: "en",
		desc: "Generative GameDev 提供的最新游戏开发资讯",
	},
	{
		id: "src-githubblog",
		title: "GitHub Blog",
		url: "https://github.blog",
		category: "社区",
		lang: "en",
		desc: "GitHub Blog 提供的最新游戏开发资讯",
	},
	{
		id: "src-godotblog",
		title: "Godot Blog",
		url: "https://godotengine.org",
		category: "社区",
		lang: "en",
		desc: "Godot Blog 提供的最新游戏开发资讯",
	},
	{
		id: "src-godotreleases",
		title: "Godot Releases",
		url: "https://github.com/godotengine/godot/releases",
		category: "社区",
		lang: "en",
		desc: "Godot Releases 提供的最新游戏开发资讯",
	},
	{
		id: "src-gridsagegames",
		title: "Grid Sage Games",
		url: "https://gridsagegames.com",
		category: "博客",
		lang: "en",
		desc: "Grid Sage Games 提供的最新游戏开发资讯",
	},
	{
		id: "src-hackernews",
		title: "Hacker News",
		url: "https://news.ycombinator.com",
		category: "社区",
		lang: "en",
		desc: "Hacker News 提供的最新游戏开发资讯",
	},
	{
		id: "src-indieinformer",
		title: "Indie Informer",
		url: "https://indieinformer.com",
		category: "社区",
		lang: "en",
		desc: "Indie Informer 提供的最新游戏开发资讯",
	},
	{
		id: "src-jetbrainsblog",
		title: "JetBrains Blog",
		url: "https://blog.jetbrains.com",
		category: "社区",
		lang: "en",
		desc: "JetBrains Blog 提供的最新游戏开发资讯",
	},
	{
		id: "src-jonasmeyerohle",
		title: "Jonas Meyer-Ohle",
		url: "https://www.jonasmeyerohle.com",
		category: "博客",
		lang: "en",
		desc: "Jonas Meyer-Ohle 提供的最新游戏开发资讯",
	},
	{
		id: "src-journalofstuff",
		title: "Journal of Stuff",
		url: "https://journalofstuff.com",
		category: "博客",
		lang: "en",
		desc: "Journal of Stuff 提供的最新游戏开发资讯",
	},
	{
		id: "src-keithburgun",
		title: "Keith Burgun",
		url: "https://keithburgun.com",
		category: "博客",
		lang: "en",
		desc: "Keith Burgun 提供的最新游戏开发资讯",
	},
	{
		id: "src-leagueofgamemakers",
		title: "League of GameMakers",
		url: "https://leagueofgamemakers.com",
		category: "社区",
		lang: "en",
		desc: "League of GameMakers 提供的最新游戏开发资讯",
	},
	{
		id: "src-level99strategy",
		title: "Level 99 Strategy",
		url: "https://www.level99strategy.com",
		category: "博客",
		lang: "en",
		desc: "Level 99 Strategy 提供的最新游戏开发资讯",
	},
	{
		id: "src-lostgarden",
		title: "Lost Garden",
		url: "https://lostgarden.home.blog",
		category: "博客",
		lang: "en",
		desc: "Lost Garden 提供的最新游戏开发资讯",
	},
	{
		id: "src-ludeonstudios",
		title: "Ludeon Studios",
		url: "https://ludeon.com",
		category: "博客",
		lang: "en",
		desc: "Ludeon Studios 提供的最新游戏开发资讯",
	},
	{
		id: "src-msbandwidth",
		title: "Más Bandwidth",
		url: "https://masbandwidth.com",
		category: "博客",
		lang: "en",
		desc: "Más Bandwidth 提供的最新游戏开发资讯",
	},
	{
		id: "src-mechanicsasmetaphor",
		title: "Mechanics as Metaphor",
		url: "https://mechanicsasmetaphor.wordpress.com",
		category: "博客",
		lang: "en",
		desc: "Mechanics as Metaphor 提供的最新游戏开发资讯",
	},
	{
		id: "src-mickwest",
		title: "Mick West",
		url: "https://www.mickwest.com",
		category: "博客",
		lang: "en",
		desc: "Mick West 提供的最新游戏开发资讯",
	},
	{
		id: "src-newtonarrative",
		title: "New to Narrative",
		url: "https://newtonarrative.com",
		category: "博客",
		lang: "en",
		desc: "New to Narrative 提供的最新游戏开发资讯",
	},
	{
		id: "src-nickycase",
		title: "Nicky Case",
		url: "https://ncase.me",
		category: "博客",
		lang: "en",
		desc: "Nicky Case 提供的最新游戏开发资讯",
	},
	{
		id: "src-nvidiagamedev",
		title: "NVIDIA Game Dev",
		url: "https://developer.nvidia.com",
		category: "社区",
		lang: "en",
		desc: "NVIDIA Game Dev 提供的最新游戏开发资讯",
	},
	{
		id: "src-nvidiaunrealengine",
		title: "NVIDIA Unreal Engine",
		url: "https://developer.nvidia.com",
		category: "社区",
		lang: "en",
		desc: "NVIDIA Unreal Engine 提供的最新游戏开发资讯",
	},
	{
		id: "src-orfeaseleftheriou",
		title: "Orfeas Eleftheriou",
		url: "https://www.orfeasel.com",
		category: "博客",
		lang: "en",
		desc: "Orfeas Eleftheriou 提供的最新游戏开发资讯",
	},
	{
		id: "src-pocketcity",
		title: "Pocket City",
		url: "https://pocketcitygame.com",
		category: "博客",
		lang: "en",
		desc: "Pocket City 提供的最新游戏开发资讯",
	},
	{
		id: "src-pragmaticengineer",
		title: "Pragmatic Engineer",
		url: "https://blog.pragmaticengineer.com",
		category: "社区",
		lang: "en",
		desc: "Pragmatic Engineer 提供的最新游戏开发资讯",
	},
	{
		id: "src-psychologyofgames",
		title: "Psychology of Games",
		url: "https://psychologyofgames.com",
		category: "博客",
		lang: "en",
		desc: "Psychology of Games 提供的最新游戏开发资讯",
	},
	{
		id: "src-pushtotalk",
		title: "Push to Talk",
		url: "https://push-to-talk.com",
		category: "博客",
		lang: "en",
		desc: "Push to Talk 提供的最新游戏开发资讯",
	},
	{
		id: "src-rampantgames",
		title: "Rampant Games",
		url: "https://rampantgames.com",
		category: "博客",
		lang: "en",
		desc: "Rampant Games 提供的最新游戏开发资讯",
	},
	{
		id: "src-raphkoster",
		title: "Raph Koster",
		url: "https://www.raphkoster.com",
		category: "博客",
		lang: "en",
		desc: "Raph Koster 提供的最新游戏开发资讯",
	},
	{
		id: "src-ratking",
		title: "Rat King",
		url: "https://ratking.co",
		category: "博客",
		lang: "en",
		desc: "Rat King 提供的最新游戏开发资讯",
	},
	{
		id: "src-rawfury",
		title: "Raw Fury",
		url: "https://rawfury.com",
		category: "博客",
		lang: "en",
		desc: "Raw Fury 提供的最新游戏开发资讯",
	},
	{
		id: "src-redblobgames",
		title: "Red Blob Games",
		url: "https://www.redblobgames.com",
		category: "博客",
		lang: "en",
		desc: "Red Blob Games 提供的最新游戏开发资讯",
	},
	{
		id: "src-renpy",
		title: "Ren'Py",
		url: "https://www.renpy.org",
		category: "社区",
		lang: "en",
		desc: "Ren'Py 提供的最新游戏开发资讯",
	},
	{
		id: "src-ryanfitzpatrick",
		title: "Ryan Fitzpatrick",
		url: "https://www.ryanjfitzpatrick.com",
		category: "博客",
		lang: "en",
		desc: "Ryan Fitzpatrick 提供的最新游戏开发资讯",
	},
	{
		id: "src-sorceressgames",
		title: "Sorceress Games",
		url: "https://sorceressgames.com",
		category: "博客",
		lang: "en",
		desc: "Sorceress Games 提供的最新游戏开发资讯",
	},
	{
		id: "src-stackoverflowblog",
		title: "Stack Overflow Blog",
		url: "https://stackoverflow.blog",
		category: "社区",
		lang: "en",
		desc: "Stack Overflow Blog 提供的最新游戏开发资讯",
	},
	{
		id: "src-strategygamestudio",
		title: "Strategy Game Studio",
		url: "https://strategygamestudio.com",
		category: "博客",
		lang: "en",
		desc: "Strategy Game Studio 提供的最新游戏开发资讯",
	},
	{
		id: "src-tophatgames",
		title: "Top Hat Games",
		url: "https://atophat.game.blog",
		category: "博客",
		lang: "en",
		desc: "Top Hat Games 提供的最新游戏开发资讯",
	},
	{
		id: "src-transportfever3",
		title: "Transport Fever 3",
		url: "https://www.transportfever3.com",
		category: "博客",
		lang: "en",
		desc: "Transport Fever 3 提供的最新游戏开发资讯",
	},
	{
		id: "src-unityblog",
		title: "Unity Blog",
		url: "https://unity.com/blog",
		category: "社区",
		lang: "en",
		desc: "Unity Blog 提供的最新游戏开发资讯",
	},
	{
		id: "src-unrealengineblog",
		title: "Unreal Engine Blog",
		url: "https://www.unrealengine.com/blog",
		category: "社区",
		lang: "en",
		desc: "Unreal Engine Blog 提供的最新游戏开发资讯",
	},
	{
		id: "src-vscodeblog",
		title: "VS Code Blog",
		url: "https://code.visualstudio.com",
		category: "社区",
		lang: "en",
		desc: "VS Code Blog 提供的最新游戏开发资讯",
	},
	{
		id: "src-wpboxdev",
		title: "wpbox.dev",
		url: "https://wpbox.dev",
		category: "博客",
		lang: "en",
		desc: "wpbox.dev 提供的最新游戏开发资讯",
	},
];
/**
 * 所有工具/资源链接（静态数据源）
 * 在前端"网址"标签页中按分类展示
 */
export const linkSource: NewsSource = {
	name: "开发工具链接",
	lang: "all",
	fetch: async () => {
		return links.map((item) => ({
			id: item.id,
			title: item.title,
			url: item.url,
			sourceName: item.category,
			extra: {
				hover: item.desc,
				info: item.category,
			},
		}));
	},
};

/** 按分类分组 */
export function getLinksByCategory(): Record<string, LinkEntry[]> {
	const groups: Record<string, LinkEntry[]> = {};
	for (const link of links) {
		if (!groups[link.category]) groups[link.category] = [];
		groups[link.category].push(link);
	}
	return groups;
}
