/**
 * 源注册表生成脚本
 *
 * 遍历 allSources，提取每个源的元数据（name/lang/category/platform），
 * 生成 src/generated/source-registry.ts，供前端使用。
 *
 * 这样新增源只需改 source 文件和注册到 allSources/socialSources，
 * LANG_MAP、SOCIAL_SOURCE_NAMES、SOCIAL_PLATFORM 自动生成。
 */
import { existsSync, mkdirSync, writeFileSync } from "fs";
import { join, relative } from "path";
import { allSources } from "./sources";
import type { NewsSource } from "./utils/types";

/** 需要提取的源元数据 */
interface SourceMeta {
	name: string;
	lang: string;
	category: string;
	platform: string;
}

function main() {
	const sources: SourceMeta[] = allSources
		.filter((s) => s.name !== "开发工具链接")
		.map((s) => ({
			name: s.name,
			lang: s.lang,
			category: s.category || "news",
			platform: s.platform || "",
		}));

	// 去重（同个源可能在 allSources 中出现多次）
	const seen = new Set<string>();
	const unique: SourceMeta[] = [];
	for (const s of sources) {
		if (!seen.has(s.name)) {
			seen.add(s.name);
			unique.push(s);
		}
	}

	// 规范化语言值：只保留 zh/en/ja，其他默认 en
	const VALID_LANGS = new Set(["zh", "en", "ja"]);
	function normalizeLang(lang: string): string {
		return VALID_LANGS.has(lang) ? lang : "en";
	}

	const langMap: Record<string, string> = {};
	const socialNames: string[] = [];
	const socialPlatform: Record<string, string> = {};

	for (const s of unique) {
		const normalized = normalizeLang(s.lang);
		langMap[s.name] = normalized;
		if (s.category === "social") {
			socialNames.push(s.name);
			socialPlatform[s.name] = s.platform;
		}
	}

	// 语言列表的排序：中文优先，英文次之，日文最后
	const langOrder: Record<string, number> = { zh: 1, en: 2, ja: 3 };
	const sorted = unique.sort(
		(a, b) => (langOrder[a.lang] || 99) - (langOrder[b.lang] || 99),
	);
	const socialNamesSorted = socialNames.sort((a, b) => {
		const pa = socialPlatform[a] || "";
		const pb = socialPlatform[b] || "";
		return pa.localeCompare(pb) || a.localeCompare(b);
	});

	// 构建文件内容
	const lines: string[] = [
		"// Auto-generated by scripts/generate-registry.ts. DO NOT EDIT.",
		"// 修改源元数据请编辑 scripts/sources/ 下的对应文件。",
		"",
		'import type { Lang } from "../../scripts/utils/types";',
		"",
		"/** 源名称 → 语言分类映射 */",
		"export const LANG_MAP: Record<string, Lang> = {",
	];

	for (const s of sorted) {
		lines.push(`\t"${escapeStr(s.name)}": "${escapeStr(normalizeLang(s.lang))}",`);
	}

	lines.push("};");
	lines.push("");
	lines.push("/** 社交源名称集合 */");
	lines.push(
		"export const SOCIAL_SOURCE_NAMES: ReadonlySet<string> = new Set([",
	);

	for (const name of socialNamesSorted) {
		lines.push(`\t"${escapeStr(name)}",`);
	}

	lines.push("]);");
	lines.push("");
	lines.push("/** 社交源名 → 平台分组映射 */");
	lines.push("export const SOCIAL_PLATFORM: Record<string, string> = {");

	for (const name of socialNamesSorted) {
		const platform = socialPlatform[name] || "";
		lines.push(`\t"${escapeStr(name)}": "${escapeStr(platform)}",`);
	}

	lines.push("};");
	lines.push("");

	const output = lines.join("\n");

	const outDir = join(process.cwd(), "src", "generated");
	mkdirSync(outDir, { recursive: true });
	const outPath = join(outDir, "source-registry.ts");
	writeFileSync(outPath, output);
	// 同时输出 JSON 供工具（update-sources-list.cjs）使用
	const jsonData = {
		langMap,
		socialNames,
		socialPlatform,
	};
	const jsonPath = join(outDir, "source-registry.json");
	writeFileSync(jsonPath, JSON.stringify(jsonData, null, 2) + "\n");
	console.log(`  → ${jsonPath}`);

	console.log(
		`✓ Generated source-registry.ts: ${Object.keys(langMap).length} 个源 (新闻 ${Object.keys(langMap).length - socialNames.length} + 社交 ${socialNames.length})`,
	);
	console.log(`  → ${outPath}`);
}

function escapeStr(s: string): string {
	return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

main();
